<?xml version="1.0" encoding="UTF-8"?>
<!--Designed and generated by Altova StyleVision Enterprise Edition 2017 rel. 3 sp1 - see http://www.altova.com/stylevision for more information.-->
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:altova="http://www.altova.com" xmlns:altova-xfi="http://www.altova.com/xslt-extensions/xbrl" xmlns:altovaext="http://www.altova.com/xslt-extensions" xmlns:array="http://www.w3.org/2005/xpath-functions/array" xmlns:clitype="clitype" xmlns:ds="http://www.w3.org/2000/09/xmldsig#" xmlns:fn="http://www.w3.org/2005/xpath-functions" xmlns:iso4217="http://www.xbrl.org/2003/iso4217" xmlns:ix="http://www.xbrl.org/2008/inlineXBRL" xmlns:java="java" xmlns:link="http://www.xbrl.org/2003/linkbase" xmlns:map="http://www.w3.org/2005/xpath-functions/map" xmlns:math="http://www.w3.org/2005/xpath-functions/math" xmlns:onlC="http://zzzs.si/b2b/onl/0001/DataTypes/ONLComplexDataType" xmlns:onlS="http://zzzs.si/b2b/onl/0001/DataTypes/ONLSimpleDataType" xmlns:onlisidt="http://zzzs.si/b2b/onl/0001/ISI/ONLISIDataTypes" xmlns:onlpzzdt="http://zzzs.si/b2b/onl/0001/PZZ/ONLPZZDataTypes" xmlns:sps="http://www.altova.com/StyleVision/user-xpath-functions" xmlns:xbrldi="http://xbrl.org/2006/xbrldi" xmlns:xbrli="http://www.xbrl.org/2003/instance" xmlns:xenc="http://www.w3.org/2001/04/xmlenc#" xmlns:xff="http://www.xbrl.org/2010/function/formula" xmlns:xfi="http://www.xbrl.org/2008/function/instance" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" exclude-result-prefixes="altova altova-xfi altovaext array clitype ds fn iso4217 ix java link map math onlC onlS onlisidt onlpzzdt sps xbrldi xbrli xenc xff xfi xlink xs xsi">
	<xsl:output version="4.0" method="html" indent="no" encoding="UTF-8" doctype-public="-//W3C//DTD HTML 4.01 Transitional//EN" doctype-system="http://www.w3.org/TR/html4/loose.dtd"/>
	<xsl:param name="SV_OutputFormat" select="'HTML'"/>
	<xsl:variable name="XML" select="/"/>
	<xsl:variable name="altova:nPxPerIn" select="96"/>
	<xsl:decimal-format name="format1" grouping-separator="." decimal-separator=","/>
	<xsl:template match="/">
		<html>
			<head>
				<title>Potrdilo o upravičeni zadržanosti od dela</title>
				<meta name="author" content="ZZZS"/>
				<meta name="generator" content="Altova StyleVision Enterprise Edition 2017 rel. 3 sp1 (http://www.altova.com)"/>
				<meta http-equiv="X-UA-Compatible" content="IE=9"/>
				<xsl:comment>[if IE]&gt;&lt;STYLE type=&quot;text/css&quot;&gt;.altova-rotate-left-textbox{filter: progid:DXImageTransform.Microsoft.BasicImage(rotation=3)} .altova-rotate-right-textbox{filter: progid:DXImageTransform.Microsoft.BasicImage(rotation=1)} &lt;/STYLE&gt;&lt;![endif]</xsl:comment>
				<xsl:comment>[if !IE]&gt;&lt;!</xsl:comment>
				<style type="text/css">.altova-rotate-left-textbox{-webkit-transform: rotate(-90deg) translate(-100%, 0%); -webkit-transform-origin: 0% 0%;-moz-transform: rotate(-90deg) translate(-100%, 0%); -moz-transform-origin: 0% 0%;-ms-transform: rotate(-90deg) translate(-100%, 0%); -ms-transform-origin: 0% 0%;}.altova-rotate-right-textbox{-webkit-transform: rotate(90deg) translate(0%, -100%); -webkit-transform-origin: 0% 0%;-moz-transform: rotate(90deg) translate(0%, -100%); -moz-transform-origin: 0% 0%;-ms-transform: rotate(90deg) translate(0%, -100%); -ms-transform-origin: 0% 0%;}</style>
				<xsl:comment>&lt;![endif]</xsl:comment>
				<style type="text/css">@page { margin-left:2cm; margin-right:2cm; margin-top:2.54cm; margin-bottom:2.2cm } @media print { br.altova-page-break { page-break-before: always; } div.altova-page-break { page-break-before: always; } }</style>
			</head>
			<body style="color:black; font-family:Open Sans; font-size:10px; keep-together:always; ">
				<xsl:for-each select="$XML">
					<span style="color:red; font-family:Open Sans; font-size:large; font-weight:bold; ">
						<xsl:text>&#160;</xsl:text>
					</span>
					<br/>
					<table style="border-bottom-style:none; border-left-style:none; border-right-style:none; border-top-style:none; " border="1" width="100%">
						<xsl:variable name="altova:CurrContextGrid_0" select="."/>
						<tbody>
							<tr>
								<td style="border-bottom-style:none; border-left-style:none; border-right-style:none; border-top-style:none; text-align:right; ">
									<span style="color:red; font-family:Open Sans; font-size:12pt; font-weight:bold; ">
										<xsl:text>PREKLICAN</xsl:text>
									</span>
								</td>
							</tr>
							<tr>
								<td style="border-bottom-style:none; border-left-style:none; border-right-style:none; border-top-style:none; text-align:left; ">
									<span style="font-family:Open Sans; font-size:14pt; font-weight:bold; ">
										<xsl:text>POTRDILO O UPRAVIČENI ZADRŽANOSTI OD DELA&#160; ŠT. </xsl:text>
									</span>
									<xsl:for-each select="$XML">
										<xsl:for-each select="onlC:PotrdiloOZadrzanostiOdDela">
											<xsl:for-each select="Podatki">
												<xsl:for-each select="StevilkaPotrdilaOZadrzanostiOdDela">
													<span style="font-family:Open Sans; font-size:14pt; font-weight:bold; ">
														<xsl:apply-templates/>
													</span>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
									</xsl:for-each>
									<br/>
									<br/>
								</td>
							</tr>
						</tbody>
					</table>
					<table style="border-bottom-style:none; border-left-style:none; border-right-style:none; border-top-style:none; " border="1" width="100%">
						<xsl:variable name="altova:CurrContextGrid_1" select="."/>
						<tbody style="font-weight:normal; ">
							<tr>
								<td style="border-bottom-style:none; border-left-style:none; border-right-style:none; border-top-style:none; width:50%; ">
									<div>
										<span style="color:green; font-family:Open Sans; font-size:8pt; ">
											<xsl:text>1 - IZVAJALEC</xsl:text>
										</span>
									</div>
								</td>
								<td style="border-bottom-style:none; border-left-style:none; border-right-style:none; border-top-style:none; width:0.1in; "/>
								<td style="border-bottom-style:none; border-left-style:none; border-right-style:none; border-top-style:none; width:50%; ">
									<div>
										<span style="color:green; font-family:Open Sans; font-size:8pt; ">
											<xsl:text>2 - ZDRAVNIK</xsl:text>
										</span>
										<span style="font-family:Open Sans; ">
											<xsl:text>&#160;</xsl:text>
										</span>
									</div>
								</td>
							</tr>
							<tr>
								<td style="border-bottom-color:green; border-bottom-style:solid; border-bottom-width:thin; border-left-color:green; border-left-style:solid; border-left-width:thin; border-right-color:green; border-right-style:solid; border-right-width:thin; border-top-color:green; border-top-style:solid; border-top-width:thin; font-weight:normal; width:50%; ">
									<div style="font-weight:normal; padding-left:0.1cm; " title="Izvajalec">
										<span style="font-family:Open Sans; ">
											<xsl:text>Številka: </xsl:text>
										</span>
										<xsl:for-each select="onlC:PotrdiloOZadrzanostiOdDela">
											<xsl:for-each select="Podatki">
												<xsl:for-each select="Izvajalec">
													<xsl:for-each select="RIZDDZStevilka">
														<span style="font-family:Open Sans; font-weight:bold; ">
															<xsl:apply-templates/>
														</span>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
									</div>
									<div style="font-weight:normal; padding-left:0.1cm; " title="Izvajalec">
										<span style="font-family:Open Sans; ">
											<xsl:text>Naziv: </xsl:text>
										</span>
										<xsl:for-each select="onlC:PotrdiloOZadrzanostiOdDela">
											<xsl:for-each select="Podatki">
												<xsl:for-each select="Izvajalec">
													<xsl:for-each select="NazivIzvajalca">
														<span style="font-family:Open Sans; font-weight:bold; ">
															<xsl:apply-templates/>
														</span>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
									</div>
								</td>
								<td style="border-bottom-color:green; border-bottom-style:none; border-left-color:green; border-left-style:none; border-right-color:green; border-right-style:none; border-top-color:green; border-top-style:none; width:0.1in; "/>
								<td style="border-bottom-color:green; border-bottom-style:solid; border-bottom-width:thin; border-left-color:green; border-left-style:solid; border-left-width:thin; border-right-color:green; border-right-style:solid; border-right-width:thin; border-top-color:green; border-top-style:solid; border-top-width:thin; font-weight:normal; width:50%; ">
									<div style="padding-left:0.1cm; ">
										<span style="font-family:Open Sans; ">
											<xsl:text>Številka: </xsl:text>
										</span>
										<xsl:for-each select="onlC:PotrdiloOZadrzanostiOdDela">
											<xsl:for-each select="Podatki">
												<xsl:for-each select="Zdravnik">
													<xsl:for-each select="RIZDDZStevilka">
														<span style="font-family:Open Sans; font-weight:bold; ">
															<xsl:apply-templates/>
														</span>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
										<br/>
										<span style="font-family:Open Sans; ">
											<xsl:text>Priimek in ime:&#160;&#160; </xsl:text>
										</span>
										<xsl:for-each select="onlC:PotrdiloOZadrzanostiOdDela">
											<xsl:for-each select="Podatki">
												<xsl:for-each select="Zdravnik">
													<xsl:for-each select="ImeZdravnika">
														<xsl:for-each select="Priimek1">
															<span style="font-family:Open Sans; font-weight:bold; ">
																<xsl:apply-templates/>
															</span>
														</xsl:for-each>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
										<xsl:if test="not(onlC:PotrdiloOZadrzanostiOdDela/Podatki/Zdravnik/ImeZdravnika/PriimekVezaj)">
											<span style="font-family:Open Sans; ">
												<xsl:text>&#160;</xsl:text>
											</span>
										</xsl:if>
										<xsl:for-each select="onlC:PotrdiloOZadrzanostiOdDela">
											<xsl:for-each select="Podatki">
												<xsl:for-each select="Zdravnik">
													<xsl:for-each select="ImeZdravnika">
														<xsl:for-each select="PriimekVezaj">
															<span style="font-family:Open Sans; font-weight:bold; ">
																<xsl:apply-templates/>
															</span>
														</xsl:for-each>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
										<xsl:for-each select="onlC:PotrdiloOZadrzanostiOdDela">
											<xsl:for-each select="Podatki">
												<xsl:for-each select="Zdravnik">
													<xsl:for-each select="ImeZdravnika">
														<xsl:for-each select="Priimek2">
															<span style="font-family:Open Sans; font-weight:bold; ">
																<xsl:apply-templates/>
															</span>
														</xsl:for-each>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
										<xsl:choose>
											<xsl:when test="not(onlC:PotrdiloOZadrzanostiOdDela/Podatki/Zdravnik/ImeZdravnika/Priimek2)"/>
											<xsl:when test="onlC:PotrdiloOZadrzanostiOdDela/Podatki/Zdravnik/ImeZdravnika/Priimek2">
												<span style="font-family:Open Sans; ">
													<xsl:text>&#160;</xsl:text>
												</span>
											</xsl:when>
										</xsl:choose>
										<xsl:for-each select="onlC:PotrdiloOZadrzanostiOdDela">
											<xsl:for-each select="Podatki">
												<xsl:for-each select="Zdravnik">
													<xsl:for-each select="ImeZdravnika">
														<xsl:for-each select="Ime1">
															<span style="font-family:Open Sans; font-weight:bold; ">
																<xsl:apply-templates/>
															</span>
														</xsl:for-each>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
										<xsl:if test="not(onlC:PotrdiloOZadrzanostiOdDela/Podatki/Zdravnik/ImeZdravnika/ImeVezaj)">
											<span style="font-family:Open Sans; ">
												<xsl:text>&#160;</xsl:text>
											</span>
										</xsl:if>
										<xsl:for-each select="onlC:PotrdiloOZadrzanostiOdDela">
											<xsl:for-each select="Podatki">
												<xsl:for-each select="Zdravnik">
													<xsl:for-each select="ImeZdravnika">
														<xsl:for-each select="ImeVezaj">
															<span style="font-family:Open Sans; font-weight:bold; ">
																<xsl:apply-templates/>
															</span>
														</xsl:for-each>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
										<xsl:for-each select="onlC:PotrdiloOZadrzanostiOdDela">
											<xsl:for-each select="Podatki">
												<xsl:for-each select="Zdravnik">
													<xsl:for-each select="ImeZdravnika">
														<xsl:for-each select="Ime2">
															<span style="font-family:Open Sans; font-weight:bold; ">
																<xsl:apply-templates/>
															</span>
														</xsl:for-each>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
										<br/>
										<span style="font-family:Open Sans; ">
											<xsl:text>Vrsta zdravnika: </xsl:text>
										</span>
										<xsl:for-each select="onlC:PotrdiloOZadrzanostiOdDela">
											<xsl:for-each select="Podatki">
												<xsl:for-each select="Zdravnik">
													<xsl:for-each select="SifraVrsteZdravnika">
														<xsl:for-each select="@sifra">
															<span style="font-family:Open Sans; font-weight:bold; ">
																<xsl:value-of select="string(.)"/>
															</span>
														</xsl:for-each>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
										<span style="font-family:Open Sans; ">
											<xsl:text>&#160;</xsl:text>
										</span>
										<xsl:choose>
											<xsl:when test="onlC:PotrdiloOZadrzanostiOdDela/Podatki/Zdravnik/SifraVrsteZdravnika/@sifra = 1">
												<span style="font-family:Open Sans; font-weight:bold; ">
													<xsl:text>OSEBNI</xsl:text>
												</span>
											</xsl:when>
											<xsl:when test="onlC:PotrdiloOZadrzanostiOdDela/Podatki/Zdravnik/SifraVrsteZdravnika/@sifra = 2">
												<span style="font-family:Open Sans; font-weight:bold; ">
													<xsl:text>NADOMESTNI</xsl:text>
												</span>
											</xsl:when>
										</xsl:choose>
									</div>
								</td>
							</tr>
						</tbody>
					</table>
					<table style="border-bottom-style:none; border-left-style:none; border-right-style:none; border-top-style:none; " border="1" width="100%">
						<xsl:variable name="altova:CurrContextGrid_2" select="."/>
						<tbody>
							<tr>
								<td style="border-bottom-style:none; border-left-style:none; border-right-style:none; border-top-style:none; width:50%; ">
									<div>
										<span style="color:green; font-family:Open Sans; font-size:8pt; ">
											<xsl:text>3 - ZAVAROVANA OSEBA </xsl:text>
										</span>
									</div>
								</td>
								<td style="border-bottom-style:none; border-left-style:none; border-right-style:none; border-top-style:none; width:0.1in; "/>
								<td style="border-bottom-style:none; border-left-style:none; border-right-style:none; border-top-style:none; width:50%; ">
									<div>
										<span style="color:green; font-family:Open Sans; font-size:8pt; ">
											<xsl:text>4 - POVEZANA OSEBA</xsl:text>
										</span>
									</div>
								</td>
							</tr>
							<tr>
								<td style="border-bottom-color:green; border-bottom-style:solid; border-bottom-width:thin; border-left-color:green; border-left-style:solid; border-left-width:thin; border-right-color:green; border-right-style:solid; border-right-width:thin; border-top-color:green; border-top-style:solid; border-top-width:thin; width:50%; ">
									<div style="border-bottom-style:none; padding-left:0.1cm; ">
										<span style="font-family:Open Sans; ">
											<xsl:text>Številka: </xsl:text>
										</span>
										<xsl:for-each select="onlC:PotrdiloOZadrzanostiOdDela">
											<xsl:for-each select="Podatki">
												<xsl:for-each select="ZavarovanaOseba">
													<xsl:for-each select="ZZZSStevilka">
														<span style="font-family:Open Sans; font-weight:bold; ">
															<xsl:apply-templates/>
														</span>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
										<br/>
										<span style="font-family:Open Sans; ">
											<xsl:text>Priimek in ime: </xsl:text>
										</span>
										<xsl:for-each select="onlC:PotrdiloOZadrzanostiOdDela">
											<xsl:for-each select="Podatki">
												<xsl:for-each select="ZavarovanaOseba">
													<xsl:for-each select="ImeOsebe">
														<xsl:for-each select="Priimek1">
															<span style="font-family:Open Sans; font-weight:bold; ">
																<xsl:apply-templates/>
															</span>
														</xsl:for-each>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
										<xsl:if test="not(onlC:PotrdiloOZadrzanostiOdDela/Podatki/ZavarovanaOseba/ImeOsebe/PriimekVezaj)">
											<span style="font-family:Open Sans; ">
												<xsl:text>&#160;</xsl:text>
											</span>
										</xsl:if>
										<xsl:for-each select="onlC:PotrdiloOZadrzanostiOdDela">
											<xsl:for-each select="Podatki">
												<xsl:for-each select="ZavarovanaOseba">
													<xsl:for-each select="ImeOsebe">
														<xsl:for-each select="PriimekVezaj">
															<span style="font-family:Open Sans; font-weight:bold; ">
																<xsl:apply-templates/>
															</span>
														</xsl:for-each>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
										<xsl:for-each select="onlC:PotrdiloOZadrzanostiOdDela">
											<xsl:for-each select="Podatki">
												<xsl:for-each select="ZavarovanaOseba">
													<xsl:for-each select="ImeOsebe">
														<xsl:for-each select="Priimek2">
															<span style="font-family:Open Sans; font-weight:bold; ">
																<xsl:apply-templates/>
															</span>
														</xsl:for-each>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
										<xsl:choose>
											<xsl:when test="not(onlC:PotrdiloOZadrzanostiOdDela/Podatki/ZavarovanaOseba/ImeOsebe/Priimek2)"/>
											<xsl:when test="onlC:PotrdiloOZadrzanostiOdDela/Podatki/ZavarovanaOseba/ImeOsebe/Priimek2">
												<span style="font-family:Open Sans; ">
													<xsl:text>&#160;</xsl:text>
												</span>
											</xsl:when>
										</xsl:choose>
										<xsl:for-each select="onlC:PotrdiloOZadrzanostiOdDela">
											<xsl:for-each select="Podatki">
												<xsl:for-each select="ZavarovanaOseba">
													<xsl:for-each select="ImeOsebe">
														<xsl:for-each select="Ime1">
															<span style="font-family:Open Sans; font-weight:bold; ">
																<xsl:apply-templates/>
															</span>
														</xsl:for-each>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
											<xsl:if test="not(Podatki/ZavarovanaOseba/ImeOsebe/ImeVezaj)">
												<span style="font-family:Open Sans; ">
													<xsl:text>&#160;</xsl:text>
												</span>
											</xsl:if>
											<xsl:for-each select="Podatki">
												<xsl:for-each select="ZavarovanaOseba">
													<xsl:for-each select="ImeOsebe">
														<xsl:for-each select="ImeVezaj">
															<span style="font-family:Open Sans; font-weight:bold; ">
																<xsl:apply-templates/>
															</span>
														</xsl:for-each>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
										<xsl:for-each select="onlC:PotrdiloOZadrzanostiOdDela">
											<xsl:for-each select="Podatki">
												<xsl:for-each select="ZavarovanaOseba">
													<xsl:for-each select="ImeOsebe">
														<xsl:for-each select="Ime2">
															<span style="font-family:Open Sans; font-weight:bold; ">
																<xsl:apply-templates/>
															</span>
														</xsl:for-each>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
										<br/>
										<span style="font-family:Open Sans; ">
											<xsl:text>Datum rojstva:</xsl:text>
										</span>
										<span>
											<xsl:text>&#160;</xsl:text>
										</span>
										<xsl:for-each select="onlC:PotrdiloOZadrzanostiOdDela">
											<xsl:for-each select="Podatki">
												<xsl:for-each select="ZavarovanaOseba">
													<xsl:for-each select="DatumRojstva">
														<span style="font-weight:bold; ">
															<xsl:variable name="altova:seqContentStrings_3">
																<xsl:value-of select="format-number(number(substring(string(string(.)), 9, 2)), '00', 'format1')"/>
																<xsl:text>.</xsl:text>
																<xsl:value-of select="format-number(number(substring(string(string(.)), 6, 2)), '00', 'format1')"/>
																<xsl:text>.</xsl:text>
																<xsl:value-of select="format-number(number(substring(string(string(string(.))), 1, 4)), '0000', 'format1')"/>
															</xsl:variable>
															<xsl:variable name="altova:sContent_3" select="string($altova:seqContentStrings_3)"/>
															<xsl:value-of select="$altova:sContent_3"/>
														</span>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
										<br/>
										<span style="font-family:Open Sans; ">
											<xsl:text>Zavarovalna podlaga: </xsl:text>
										</span>
										<xsl:for-each select="onlC:PotrdiloOZadrzanostiOdDela">
											<xsl:for-each select="Podatki">
												<xsl:for-each select="ZavarovanaOseba">
													<xsl:for-each select="SifraZavarovalnePodlageIzOZZ">
														<xsl:for-each select="@sifra">
															<span style="font-family:Open Sans; font-weight:bold; ">
																<xsl:value-of select="string(.)"/>
															</span>
														</xsl:for-each>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
										<br/>
										<span style="font-family:Open Sans; ">
											<xsl:text>Enota ZZZS zavarovanja: </xsl:text>
										</span>
										<xsl:for-each select="onlC:PotrdiloOZadrzanostiOdDela">
											<xsl:for-each select="Podatki">
												<xsl:for-each select="ZavarovanaOseba">
													<xsl:for-each select="SifraIzpostaveLokacijeZaposlitve">
														<xsl:for-each select="@sifra">
															<span style="font-family:Open Sans; font-weight:bold; ">
																<xsl:value-of select="string(.)"/>
															</span>
														</xsl:for-each>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
										<br/>
									</div>
								</td>
								<td style="border-bottom-color:green; border-bottom-style:none; border-left-color:green; border-left-style:none; border-right-color:green; border-right-style:none; border-top-color:green; border-top-style:none; width:0.1in; "/>
								<td style="border-bottom-color:green; border-bottom-style:solid; border-bottom-width:thin; border-left-color:green; border-left-style:solid; border-left-width:thin; border-right-color:green; border-right-style:solid; border-right-width:thin; border-top-color:green; border-top-style:solid; border-top-width:thin; width:50%; ">
									<div style="border-left-style:none; border-top-style:none; padding-left:0.1cm; ">
										<span style="font-family:Open Sans; ">
											<xsl:text>Priimek in ime: </xsl:text>
										</span>
										<xsl:for-each select="onlC:PotrdiloOZadrzanostiOdDela">
											<xsl:for-each select="Podatki">
												<xsl:for-each select="PovezanaOseba">
													<xsl:for-each select="ImeOsebe">
														<xsl:for-each select="Priimek1">
															<span style="font-family:Open Sans; font-weight:bold; ">
																<xsl:apply-templates/>
															</span>
														</xsl:for-each>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
										<xsl:if test="not(onlC:PotrdiloOZadrzanostiOdDela/Podatki/PovezanaOseba/ImeOsebe/PriimekVezaj)">
											<span style="font-family:Open Sans; ">
												<xsl:text>&#160;</xsl:text>
											</span>
										</xsl:if>
										<xsl:for-each select="onlC:PotrdiloOZadrzanostiOdDela">
											<xsl:for-each select="Podatki">
												<xsl:for-each select="PovezanaOseba">
													<xsl:for-each select="ImeOsebe">
														<xsl:for-each select="PriimekVezaj">
															<span style="font-family:Open Sans; font-weight:bold; ">
																<xsl:apply-templates/>
															</span>
														</xsl:for-each>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
										<xsl:for-each select="onlC:PotrdiloOZadrzanostiOdDela">
											<xsl:for-each select="Podatki">
												<xsl:for-each select="PovezanaOseba">
													<xsl:for-each select="ImeOsebe">
														<xsl:for-each select="Priimek2">
															<span style="font-family:Open Sans; font-weight:bold; ">
																<xsl:apply-templates/>
															</span>
														</xsl:for-each>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
										<xsl:choose>
											<xsl:when test="not(onlC:PotrdiloOZadrzanostiOdDela/Podatki/PovezanaOseba/ImeOsebe/Priimek2)"/>
											<xsl:when test="onlC:PotrdiloOZadrzanostiOdDela/Podatki/PovezanaOseba/ImeOsebe/Priimek2">
												<span style="font-family:Open Sans; ">
													<xsl:text>&#160;</xsl:text>
												</span>
											</xsl:when>
										</xsl:choose>
										<xsl:for-each select="onlC:PotrdiloOZadrzanostiOdDela">
											<xsl:for-each select="Podatki">
												<xsl:for-each select="PovezanaOseba">
													<xsl:for-each select="ImeOsebe">
														<xsl:for-each select="Ime1">
															<span style="font-family:Open Sans; font-weight:bold; ">
																<xsl:apply-templates/>
															</span>
														</xsl:for-each>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
										<xsl:if test="not(onlC:PotrdiloOZadrzanostiOdDela/Podatki/PovezanaOseba/ImeOsebe/ImeVezaj)">
											<span style="font-family:Open Sans; ">
												<xsl:text>&#160;</xsl:text>
											</span>
										</xsl:if>
										<xsl:for-each select="onlC:PotrdiloOZadrzanostiOdDela">
											<xsl:for-each select="Podatki">
												<xsl:for-each select="PovezanaOseba">
													<xsl:for-each select="ImeOsebe">
														<xsl:for-each select="ImeVezaj">
															<span style="font-family:Open Sans; font-weight:bold; ">
																<xsl:apply-templates/>
															</span>
														</xsl:for-each>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
										<xsl:for-each select="onlC:PotrdiloOZadrzanostiOdDela">
											<xsl:for-each select="Podatki">
												<xsl:for-each select="PovezanaOseba">
													<xsl:for-each select="ImeOsebe">
														<xsl:for-each select="Ime2">
															<span style="font-family:Open Sans; font-weight:bold; ">
																<xsl:apply-templates/>
															</span>
														</xsl:for-each>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
										<br/>
										<span style="font-family:Open Sans; ">
											<xsl:text>Datum rojstva: </xsl:text>
										</span>
										<xsl:for-each select="onlC:PotrdiloOZadrzanostiOdDela">
											<xsl:for-each select="Podatki">
												<xsl:for-each select="PovezanaOseba">
													<xsl:for-each select="DatumRojstva">
														<span style="font-family:Open Sans; font-weight:bold; ">
															<xsl:variable name="altova:seqContentStrings_4">
																<xsl:value-of select="format-number(number(substring(string(string(.)), 9, 2)), '00', 'format1')"/>
																<xsl:text>. </xsl:text>
																<xsl:value-of select="format-number(number(substring(string(string(.)), 6, 2)), '00', 'format1')"/>
																<xsl:text>. </xsl:text>
																<xsl:value-of select="format-number(number(substring(string(string(string(.))), 1, 4)), '0000', 'format1')"/>
															</xsl:variable>
															<xsl:variable name="altova:sContent_4" select="string($altova:seqContentStrings_4)"/>
															<xsl:value-of select="$altova:sContent_4"/>
														</span>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
										<br/>
										<span style="font-family:Open Sans; ">
											<xsl:text>Vrsta povezane osebe: </xsl:text>
										</span>
										<xsl:for-each select="onlC:PotrdiloOZadrzanostiOdDela">
											<xsl:for-each select="Podatki">
												<xsl:for-each select="PovezanaOseba">
													<xsl:for-each select="SifraVrstePovezaneOsebe">
														<xsl:for-each select="@sifra">
															<span style="font-family:Open Sans; font-weight:bold; ">
																<xsl:value-of select="string(.)"/>
															</span>
														</xsl:for-each>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
										<xsl:for-each select="ONL">
											<xsl:for-each select="VhodniPodatki">
												<xsl:for-each select="VsebinskiPodatki">
													<xsl:for-each select="Telo">
														<xsl:for-each select="Zapisovanje">
															<xsl:for-each select="ZadrzanostOdDela">
																<xsl:for-each select="onlC:PotrdiloOZadrzanostiOdDela">
																	<xsl:for-each select="Podatki">
																		<xsl:for-each select="PovezanaOseba">
																			<xsl:for-each select="SifraVrstePovezaneOsebe">
																				<xsl:for-each select="@sifra">
																					<span style="font-family:Open Sans; font-weight:bold; ">
																						<xsl:value-of select="string(.)"/>
																					</span>
																				</xsl:for-each>
																			</xsl:for-each>
																		</xsl:for-each>
																	</xsl:for-each>
																</xsl:for-each>
															</xsl:for-each>
														</xsl:for-each>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
										<span style="font-family:Open Sans; ">
											<xsl:text>&#160;</xsl:text>
										</span>
										<xsl:choose>
											<xsl:when test="onlC:PotrdiloOZadrzanostiOdDela/Podatki/PovezanaOseba/SifraVrstePovezaneOsebe/@sifra=1">
												<span style="font-family:Open Sans; font-weight:bold; ">
													<xsl:text>PARTNER</xsl:text>
												</span>
											</xsl:when>
											<xsl:when test="onlC:PotrdiloOZadrzanostiOdDela/Podatki/PovezanaOseba/SifraVrstePovezaneOsebe/@sifra=2">
												<span style="font-family:Open Sans; font-weight:bold; ">
													<xsl:text>OTROK</xsl:text>
												</span>
											</xsl:when>
											<xsl:when test="onlC:PotrdiloOZadrzanostiOdDela/Podatki/PovezanaOseba/SifraVrstePovezaneOsebe/@sifra=3">
												<span style="font-family:Open Sans; font-weight:bold; ">
													<xsl:text>DRUGO</xsl:text>
												</span>
											</xsl:when>
										</xsl:choose>
										<br/>
									</div>
								</td>
							</tr>
						</tbody>
					</table>
					<table style="border-bottom-style:none; border-left-style:none; border-right-style:none; border-top-style:none; " border="1" width="100%">
						<xsl:variable name="altova:CurrContextGrid_5" select="."/>
						<tbody>
							<tr>
								<td style="border-bottom-style:none; border-left-style:none; border-right-style:none; border-top-style:none; width:50%; ">
									<div>
										<span style="color:green; font-family:Open Sans; font-size:8pt; ">
											<xsl:text>5 - PRVI DAN ZADRŽANOSTI</xsl:text>
										</span>
										<span style="color:gray; font-family:Open Sans; font-size:8pt; ">
											<xsl:text>&#160; </xsl:text>
										</span>
										<span style="font-family:Open Sans; ">
											<xsl:text>&#160; </xsl:text>
										</span>
									</div>
								</td>
								<td style="border-bottom-style:none; border-left-style:none; border-right-style:none; border-top-style:none; width:0.1in; "/>
								<td style="border-bottom-style:none; border-left-style:none; border-right-style:none; border-top-style:none; width:50%; ">
									<div>
										<span style="color:green; font-family:Open Sans; font-size:8pt; ">
											<xsl:text>6 - ZADNJI DAN ZADRŽANOSTI</xsl:text>
										</span>
									</div>
								</td>
							</tr>
							<tr>
								<td style="border-bottom-color:green; border-bottom-style:solid; border-bottom-width:thin; border-left-color:green; border-left-style:solid; border-left-width:thin; border-right-color:green; border-right-style:solid; border-right-width:thin; border-top-color:green; border-top-style:solid; border-top-width:thin; width:50%; ">
									<div style="padding-left:0.1cm; ">
										<span style="font-family:Open Sans; ">
											<xsl:text>Prvi dan zadržanosti od:&#160; </xsl:text>
										</span>
										<xsl:for-each select="onlC:PotrdiloOZadrzanostiOdDela">
											<xsl:for-each select="Podatki">
												<xsl:for-each select="PrviDanZadrzanosti">
													<xsl:for-each select="DatumPrvegaDneZadrzanosti">
														<span style="font-family:Open Sans; font-weight:bold; ">
															<xsl:variable name="altova:seqContentStrings_6">
																<xsl:value-of select="format-number(number(substring(string(string(.)), 9, 2)), '00', 'format1')"/>
																<xsl:text>. </xsl:text>
																<xsl:value-of select="format-number(number(substring(string(string(.)), 6, 2)), '00', 'format1')"/>
																<xsl:text>. </xsl:text>
																<xsl:value-of select="format-number(number(substring(string(string(string(.))), 1, 4)), '0000', 'format1')"/>
															</xsl:variable>
															<xsl:variable name="altova:sContent_6" select="string($altova:seqContentStrings_6)"/>
															<xsl:value-of select="$altova:sContent_6"/>
														</span>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
										<xsl:for-each select="ONL">
											<xsl:for-each select="VhodniPodatki">
												<xsl:for-each select="VsebinskiPodatki">
													<xsl:for-each select="Telo">
														<xsl:for-each select="Zapisovanje">
															<xsl:for-each select="ZadrzanostOdDela">
																<xsl:for-each select="onlC:PotrdiloOZadrzanostiOdDela">
																	<xsl:for-each select="Podatki">
																		<xsl:for-each select="PrviDanZadrzanosti">
																			<xsl:for-each select="DatumPrvegaDneZadrzanosti">
																				<span style="font-family:Open Sans; font-weight:bold; ">
																					<xsl:variable name="altova:seqContentStrings_7">
																						<xsl:value-of select="format-number(number(substring(string(string(.)), 9, 2)), '00', 'format1')"/>
																						<xsl:text>. </xsl:text>
																						<xsl:value-of select="format-number(number(substring(string(string(.)), 6, 2)), '00', 'format1')"/>
																						<xsl:text>. </xsl:text>
																						<xsl:value-of select="format-number(number(substring(string(string(string(.))), 1, 4)), '0000', 'format1')"/>
																					</xsl:variable>
																					<xsl:variable name="altova:sContent_7" select="string($altova:seqContentStrings_7)"/>
																					<xsl:value-of select="$altova:sContent_7"/>
																				</span>
																			</xsl:for-each>
																		</xsl:for-each>
																	</xsl:for-each>
																</xsl:for-each>
															</xsl:for-each>
														</xsl:for-each>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
										<br/>
										<span style="font-family:Open Sans; ">
											<xsl:text>Prejšnja zadržanost od dela-recidiv </xsl:text>
										</span>
										<br/>
										<span style="font-family:Open Sans; ">
											<xsl:text>od: </xsl:text>
										</span>
										<xsl:for-each select="onlC:PotrdiloOZadrzanostiOdDela">
											<xsl:for-each select="Podatki">
												<xsl:for-each select="PrviDanZadrzanosti">
													<xsl:for-each select="PrejsnjaZadrzanostRecidiv">
														<xsl:for-each select="DatumOd">
															<span style="font-family:Open Sans; font-weight:bold; ">
																<xsl:variable name="altova:seqContentStrings_8">
																	<xsl:value-of select="format-number(number(substring(string(string(.)), 9, 2)), '00', 'format1')"/>
																	<xsl:text>. </xsl:text>
																	<xsl:value-of select="format-number(number(substring(string(string(.)), 6, 2)), '00', 'format1')"/>
																	<xsl:text>. </xsl:text>
																	<xsl:value-of select="format-number(number(substring(string(string(string(.))), 1, 4)), '0000', 'format1')"/>
																</xsl:variable>
																<xsl:variable name="altova:sContent_8" select="string($altova:seqContentStrings_8)"/>
																<xsl:value-of select="$altova:sContent_8"/>
															</span>
														</xsl:for-each>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
										<span style="font-family:Open Sans; ">
											<xsl:text>&#160;&#160;&#160; do: </xsl:text>
										</span>
										<xsl:for-each select="onlC:PotrdiloOZadrzanostiOdDela">
											<xsl:for-each select="Podatki">
												<xsl:for-each select="PrviDanZadrzanosti">
													<xsl:for-each select="PrejsnjaZadrzanostRecidiv">
														<xsl:for-each select="DatumDo">
															<span style="font-family:Open Sans; font-weight:bold; ">
																<xsl:variable name="altova:seqContentStrings_9">
																	<xsl:value-of select="format-number(number(substring(string(string(.)), 9, 2)), '00', 'format1')"/>
																	<xsl:text>. </xsl:text>
																	<xsl:value-of select="format-number(number(substring(string(string(.)), 6, 2)), '00', 'format1')"/>
																	<xsl:text>. </xsl:text>
																	<xsl:value-of select="format-number(number(substring(string(string(string(.))), 1, 4)), '0000', 'format1')"/>
																</xsl:variable>
																<xsl:variable name="altova:sContent_9" select="string($altova:seqContentStrings_9)"/>
																<xsl:value-of select="$altova:sContent_9"/>
															</span>
														</xsl:for-each>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
									</div>
								</td>
								<td style="border-bottom-color:green; border-bottom-style:none; border-left-color:green; border-left-style:none; border-right-color:green; border-right-style:none; border-top-color:green; border-top-style:none; width:0.1in; "/>
								<td style="border-bottom-color:green; border-bottom-style:solid; border-bottom-width:thin; border-left-color:green; border-left-style:solid; border-left-width:thin; border-right-color:green; border-right-style:solid; border-right-width:thin; border-top-color:green; border-top-style:solid; border-top-width:thin; width:50%; ">
									<div style="font-weight:normal; ">
										<span style="font-family:Open Sans; ">
											<xsl:text>&#160;&#160;&#160;&#160;&#160;&#160;&#160; Za diagnozo:&#160;&#160;&#160;&#160;&#160; Za razlog:&#160;&#160;&#160;&#160;&#160; Za plačnika:</xsl:text>
										</span>
										<br/>
										<span style="font-family:Open Sans; ">
											<xsl:text>&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </xsl:text>
										</span>
										<xsl:choose>
											<xsl:when test="onlC:PotrdiloOZadrzanostiOdDela/Podatki/ZadnjiDanZadrzanosti/ZaDiagnozo=&apos;true&apos;">
												<span style="font-family:Open Sans; font-weight:bold; ">
													<xsl:text>DA</xsl:text>
												</span>
											</xsl:when>
											<xsl:when test="onlC:PotrdiloOZadrzanostiOdDela/Podatki/ZadnjiDanZadrzanosti/ZaDiagnozo=&apos;false&apos;">
												<span style="font-family:Open Sans; font-weight:bold; ">
													<xsl:text>NE</xsl:text>
												</span>
											</xsl:when>
										</xsl:choose>
										<span style="font-family:Open Sans; ">
											<xsl:text>&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </xsl:text>
										</span>
										<xsl:choose>
											<xsl:when test="onlC:PotrdiloOZadrzanostiOdDela/Podatki/ZadnjiDanZadrzanosti/ZaRazlog=&apos;true&apos;">
												<span style="font-family:Open Sans; font-weight:bold; ">
													<xsl:text>DA</xsl:text>
												</span>
											</xsl:when>
											<xsl:when test="onlC:PotrdiloOZadrzanostiOdDela/Podatki/ZadnjiDanZadrzanosti/ZaRazlog=&apos;false&apos;">
												<span style="font-family:Open Sans; font-weight:bold; ">
													<xsl:text>NE</xsl:text>
												</span>
											</xsl:when>
										</xsl:choose>
										<span style="font-family:Open Sans; ">
											<xsl:text>&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </xsl:text>
										</span>
										<xsl:choose>
											<xsl:when test="onlC:PotrdiloOZadrzanostiOdDela/Podatki/ZadnjiDanZadrzanosti/ZaPlacnika=&apos;true&apos;">
												<span style="font-family:Open Sans; font-weight:bold; ">
													<xsl:text>DA</xsl:text>
												</span>
											</xsl:when>
											<xsl:when test="onlC:PotrdiloOZadrzanostiOdDela/Podatki/ZadnjiDanZadrzanosti/ZaPlacnika=&apos;false&apos;">
												<span style="font-family:Open Sans; font-weight:bold; ">
													<xsl:text>NE</xsl:text>
												</span>
											</xsl:when>
										</xsl:choose>
									</div>
								</td>
							</tr>
						</tbody>
					</table>
					<table style="border-bottom-style:none; border-left-style:none; border-right-style:none; border-top-style:none; " border="1" width="100%">
						<xsl:variable name="altova:CurrContextGrid_10" select="."/>
						<tbody>
							<tr>
								<td style="border-bottom-style:none; border-left-style:none; border-right-style:none; border-top-style:none; width:50%; ">
									<div>
										<span style="color:green; font-family:Open Sans; font-size:8pt; ">
											<xsl:text>7 - ZAVEZANEC</xsl:text>
										</span>
									</div>
								</td>
								<td style="border-bottom-style:none; border-left-style:none; border-right-style:none; border-top-style:none; width:0.1in; "/>
								<td style="border-bottom-style:none; border-left-style:none; border-right-style:none; border-top-style:none; width:50%; ">
									<div>
										<span style="color:green; font-family:Open Sans; font-size:8pt; ">
											<xsl:text>8 - ODLOČBA</xsl:text>
										</span>
									</div>
								</td>
							</tr>
							<tr>
								<td style="border-bottom-color:green; border-bottom-style:solid; border-bottom-width:thin; border-left-color:green; border-left-style:solid; border-left-width:thin; border-right-color:green; border-right-style:solid; border-right-width:thin; border-top-color:green; border-top-style:solid; border-top-width:thin; width:50%; ">
									<div style="border-left-style:none; border-top-style:none; padding-left:0.1cm; ">
										<span style="font-family:Open Sans; ">
											<xsl:text>Naziv: </xsl:text>
										</span>
										<xsl:for-each select="onlC:PotrdiloOZadrzanostiOdDela">
											<xsl:for-each select="Podatki">
												<xsl:for-each select="Zavezanec">
													<xsl:for-each select="NazivZavezanca">
														<span style="font-family:Open Sans; font-weight:bold; ">
															<xsl:apply-templates/>
														</span>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
										<br/>
										<span style="font-family:Open Sans; ">
											<xsl:text>Registrska št.: </xsl:text>
										</span>
										<xsl:for-each select="onlC:PotrdiloOZadrzanostiOdDela">
											<xsl:for-each select="Podatki">
												<xsl:for-each select="Zavezanec">
													<xsl:for-each select="RegistrskaStevilka">
														<span style="font-family:Open Sans; font-weight:bold; ">
															<xsl:apply-templates/>
														</span>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
										<br/>
										<span style="font-family:Open Sans; ">
											<xsl:text>Šifra dejavnosti: </xsl:text>
										</span>
										<xsl:for-each select="onlC:PotrdiloOZadrzanostiOdDela">
											<xsl:for-each select="Podatki">
												<xsl:for-each select="Zavezanec">
													<xsl:for-each select="SifraDejavnosti">
														<xsl:for-each select="@sifra">
															<span style="font-family:Open Sans; font-weight:bold; ">
																<xsl:value-of select="string(.)"/>
															</span>
														</xsl:for-each>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
										<span style="font-family:Open Sans; ">
											<xsl:text>&#160;&#160;&#160;&#160; Zap.št.potrdila: </xsl:text>
										</span>
										<xsl:for-each select="onlC:PotrdiloOZadrzanostiOdDela">
											<xsl:for-each select="Podatki">
												<xsl:for-each select="Zavezanec">
													<xsl:for-each select="ZaporednaStevilkaPotrdila">
														<span style="font-family:Open Sans; font-weight:bold; ">
															<xsl:apply-templates/>
														</span>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
									</div>
								</td>
								<td style="border-bottom-color:green; border-bottom-style:none; border-left-color:green; border-left-style:none; border-right-color:green; border-right-style:none; border-top-color:green; border-top-style:none; width:0.1in; "/>
								<td style="border-bottom-color:green; border-bottom-style:solid; border-bottom-width:thin; border-left-color:green; border-left-style:solid; border-left-width:thin; border-right-color:green; border-right-style:solid; border-right-width:thin; border-top-color:green; border-top-style:solid; border-top-width:thin; width:50%; ">
									<div style="padding-left:0.1cm; ">
										<span style="font-family:Open Sans; ">
											<xsl:text>Zadržan po odločbi št.: </xsl:text>
										</span>
										<xsl:for-each select="onlC:PotrdiloOZadrzanostiOdDela">
											<xsl:for-each select="Podatki">
												<xsl:for-each select="Odlocba">
													<xsl:for-each select="StevilkaOdlocbe">
														<span style="font-family:Open Sans; font-weight:bold; ">
															<xsl:apply-templates/>
														</span>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
										<br/>
										<span style="font-family:Open Sans; ">
											<xsl:text>&#160; </xsl:text>
										</span>
										<xsl:for-each select="onlC:PotrdiloOZadrzanostiOdDela">
											<xsl:for-each select="Podatki">
												<xsl:for-each select="Odlocba">
													<xsl:for-each select="SifraIzdajatelja">
														<xsl:for-each select="@sifra">
															<span style="font-family:Open Sans; font-weight:bold; ">
																<xsl:value-of select="string(.)"/>
															</span>
														</xsl:for-each>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
										<span style="font-family:Open Sans; ">
											<xsl:text>&#160; </xsl:text>
										</span>
										<xsl:choose>
											<xsl:when test="onlC:PotrdiloOZadrzanostiOdDela/Podatki/Odlocba/SifraIzdajatelja/@sifra=1">
												<span style="font-family:Open Sans; font-weight:bold; ">
													<xsl:text>IMENOVANEGA ZDRAVNIKA</xsl:text>
												</span>
											</xsl:when>
											<xsl:when test="onlC:PotrdiloOZadrzanostiOdDela/Podatki/Odlocba/SifraIzdajatelja/@sifra=2">
												<span style="font-family:Open Sans; font-weight:bold; ">
													<xsl:text>ZDRAVSTVENE KOMISIJE</xsl:text>
												</span>
											</xsl:when>
										</xsl:choose>
									</div>
									<div style="padding-left:0.1cm; ">
										<span style="font-family:Open Sans; ">
											<xsl:text>do: </xsl:text>
										</span>
										<xsl:for-each select="onlC:PotrdiloOZadrzanostiOdDela">
											<xsl:for-each select="Podatki">
												<xsl:for-each select="Odlocba">
													<xsl:for-each select="DatumZadrzanostiPoOdlocbiDo">
														<span style="font-family:Open Sans; font-weight:bold; ">
															<xsl:variable name="altova:seqContentStrings_11">
																<xsl:value-of select="format-number(number(substring(string(string(.)), 9, 2)), '00', 'format1')"/>
																<xsl:text>. </xsl:text>
																<xsl:value-of select="format-number(number(substring(string(string(.)), 6, 2)), '00', 'format1')"/>
																<xsl:text>. </xsl:text>
																<xsl:value-of select="format-number(number(substring(string(string(string(.))), 1, 4)), '0000', 'format1')"/>
															</xsl:variable>
															<xsl:variable name="altova:sContent_11" select="string($altova:seqContentStrings_11)"/>
															<xsl:value-of select="$altova:sContent_11"/>
														</span>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
									</div>
								</td>
							</tr>
						</tbody>
					</table>
					<table style="border-bottom-style:none; border-left-style:none; border-right-style:none; border-top-style:none; " border="1" width="100%">
						<xsl:variable name="altova:CurrContextGrid_12" select="."/>
						<tbody>
							<tr>
								<td style="border-bottom-style:none; border-left-style:none; border-right-style:none; border-top-style:none; width:50%; ">
									<div>
										<span style="color:green; font-family:Open Sans; font-size:8pt; ">
											<xsl:text>9 - NAPOTEN NA IK </xsl:text>
										</span>
										<span style="color:gray; font-family:Open Sans; font-size:8pt; ">
											<xsl:text>&#160;</xsl:text>
										</span>
										<span style="font-family:Open Sans; ">
											<xsl:text>&#160;</xsl:text>
										</span>
									</div>
								</td>
								<td style="border-bottom-style:none; border-left-style:none; border-right-style:none; border-top-style:none; width:0.1in; "/>
								<td style="border-bottom-style:none; border-left-style:none; border-right-style:none; border-top-style:none; width:50%; ">
									<div>
										<span style="color:green; font-family:Open Sans; font-size:8pt; ">
											<xsl:text>10 - ZADRŽANOST OD DELA</xsl:text>
										</span>
									</div>
								</td>
							</tr>
							<tr>
								<td style="border-bottom-style:solid; border-bottom-width:thin; border-color:green; border-left-color:green; border-left-style:solid; border-left-width:thin; border-right-color:green; border-right-style:solid; border-right-width:thin; border-top-color:green; border-top-style:solid; border-top-width:thin; width:50%; ">
									<div style="padding-left:0.1cm; ">
										<span style="font-family:Open Sans; ">
											<xsl:text>Napoten na IK dne: </xsl:text>
										</span>
										<xsl:for-each select="onlC:PotrdiloOZadrzanostiOdDela">
											<xsl:for-each select="Podatki">
												<xsl:for-each select="NapotitevNaInvalidskoKomisijo">
													<xsl:for-each select="DatumNapotitve">
														<span style="font-family:Open Sans; font-weight:bold; ">
															<xsl:variable name="altova:seqContentStrings_13">
																<xsl:value-of select="format-number(number(substring(string(string(.)), 9, 2)), '00', 'format1')"/>
																<xsl:text>. </xsl:text>
																<xsl:value-of select="format-number(number(substring(string(string(.)), 6, 2)), '00', 'format1')"/>
																<xsl:text>. </xsl:text>
																<xsl:value-of select="format-number(number(substring(string(string(string(.))), 1, 4)), '0000', 'format1')"/>
															</xsl:variable>
															<xsl:variable name="altova:sContent_13" select="string($altova:seqContentStrings_13)"/>
															<xsl:value-of select="$altova:sContent_13"/>
														</span>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
										<br/>
										<span style="font-family:Open Sans; ">
											<xsl:text>Postopek zaključen: </xsl:text>
										</span>
										<xsl:choose>
											<xsl:when test="onlC:PotrdiloOZadrzanostiOdDela/Podatki/NapotitevNaInvalidskoKomisijo/OznakaZakljuckaPostopkaInvalidskeKomisije=&apos;true&apos;">
												<span style="font-family:Open Sans; font-weight:bold; ">
													<xsl:text>DA</xsl:text>
												</span>
											</xsl:when>
											<xsl:when test="onlC:PotrdiloOZadrzanostiOdDela/Podatki/NapotitevNaInvalidskoKomisijo/OznakaZakljuckaPostopkaInvalidskeKomisije=&apos;false&apos;">
												<span style="font-family:Open Sans; font-weight:bold; ">
													<xsl:text>NE</xsl:text>
												</span>
											</xsl:when>
										</xsl:choose>
									</div>
								</td>
								<td style="border-bottom-style:none; border-color:green; border-left-color:green; border-left-style:none; border-right-color:green; border-right-style:none; border-top-color:green; border-top-style:none; width:0.1in; "/>
								<td style="border-bottom-style:solid; border-bottom-width:thin; border-color:green; border-left-color:green; border-left-style:solid; border-left-width:thin; border-right-color:green; border-right-style:solid; border-right-width:thin; border-top-color:green; border-top-style:solid; border-top-width:thin; width:50%; ">
									<div style="padding-left:0.1cm; ">
										<span style="font-family:Open Sans; ">
											<xsl:text>Polni delovni čas od: </xsl:text>
										</span>
										<xsl:for-each select="onlC:PotrdiloOZadrzanostiOdDela">
											<xsl:for-each select="Podatki">
												<xsl:for-each select="CasZadrzanostiOdDela">
													<xsl:for-each select="ZadrzanostZaPolniDelovniCas">
														<xsl:for-each select="DatumOd">
															<span style="font-family:Open Sans; font-weight:bold; ">
																<xsl:variable name="altova:seqContentStrings_14">
																	<xsl:value-of select="format-number(number(substring(string(string(.)), 9, 2)), '00', 'format1')"/>
																	<xsl:text>. </xsl:text>
																	<xsl:value-of select="format-number(number(substring(string(string(.)), 6, 2)), '00', 'format1')"/>
																	<xsl:text>. </xsl:text>
																	<xsl:value-of select="format-number(number(substring(string(string(string(.))), 1, 4)), '0000', 'format1')"/>
																</xsl:variable>
																<xsl:variable name="altova:sContent_14" select="string($altova:seqContentStrings_14)"/>
																<xsl:value-of select="$altova:sContent_14"/>
															</span>
														</xsl:for-each>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
										<span style="font-family:Open Sans; ">
											<xsl:text> do: </xsl:text>
										</span>
										<xsl:for-each select="onlC:PotrdiloOZadrzanostiOdDela">
											<xsl:for-each select="Podatki">
												<xsl:for-each select="CasZadrzanostiOdDela">
													<xsl:for-each select="ZadrzanostZaPolniDelovniCas">
														<xsl:for-each select="DatumDo">
															<span style="font-family:Open Sans; font-weight:bold; ">
																<xsl:variable name="altova:seqContentStrings_15">
																	<xsl:value-of select="format-number(number(substring(string(string(.)), 9, 2)), '00', 'format1')"/>
																	<xsl:text>. </xsl:text>
																	<xsl:value-of select="format-number(number(substring(string(string(.)), 6, 2)), '00', 'format1')"/>
																	<xsl:text>. </xsl:text>
																	<xsl:value-of select="format-number(number(substring(string(string(string(.))), 1, 4)), '0000', 'format1')"/>
																</xsl:variable>
																<xsl:variable name="altova:sContent_15" select="string($altova:seqContentStrings_15)"/>
																<xsl:value-of select="$altova:sContent_15"/>
															</span>
														</xsl:for-each>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
										<br/>
										<span style="font-family:Open Sans; ">
											<xsl:text>Krajši delovni čas od: </xsl:text>
										</span>
										<xsl:for-each select="onlC:PotrdiloOZadrzanostiOdDela">
											<xsl:for-each select="Podatki">
												<xsl:for-each select="CasZadrzanostiOdDela">
													<xsl:for-each select="ZadrzanostZaKrajsiDelovniCas">
														<xsl:for-each select="DatumOd">
															<span style="font-family:Open Sans; font-weight:bold; ">
																<xsl:variable name="altova:seqContentStrings_16">
																	<xsl:value-of select="format-number(number(substring(string(string(.)), 9, 2)), '00', 'format1')"/>
																	<xsl:text>. </xsl:text>
																	<xsl:value-of select="format-number(number(substring(string(string(.)), 6, 2)), '00', 'format1')"/>
																	<xsl:text>. </xsl:text>
																	<xsl:value-of select="format-number(number(substring(string(string(string(.))), 1, 4)), '0000', 'format1')"/>
																</xsl:variable>
																<xsl:variable name="altova:sContent_16" select="string($altova:seqContentStrings_16)"/>
																<xsl:value-of select="$altova:sContent_16"/>
															</span>
														</xsl:for-each>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
										<span style="font-family:Open Sans; ">
											<xsl:text> do: </xsl:text>
										</span>
										<xsl:for-each select="onlC:PotrdiloOZadrzanostiOdDela">
											<xsl:for-each select="Podatki">
												<xsl:for-each select="CasZadrzanostiOdDela">
													<xsl:for-each select="ZadrzanostZaKrajsiDelovniCas">
														<xsl:for-each select="DatumDo">
															<span style="font-family:Open Sans; font-weight:bold; ">
																<xsl:variable name="altova:seqContentStrings_17">
																	<xsl:value-of select="format-number(number(substring(string(string(.)), 9, 2)), '00', 'format1')"/>
																	<xsl:text>. </xsl:text>
																	<xsl:value-of select="format-number(number(substring(string(string(.)), 6, 2)), '00', 'format1')"/>
																	<xsl:text>. </xsl:text>
																	<xsl:value-of select="format-number(number(substring(string(string(string(.))), 1, 4)), '0000', 'format1')"/>
																</xsl:variable>
																<xsl:variable name="altova:sContent_17" select="string($altova:seqContentStrings_17)"/>
																<xsl:value-of select="$altova:sContent_17"/>
															</span>
														</xsl:for-each>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
										<br/>
										<span style="font-family:Open Sans; ">
											<xsl:text>Dolžan delati: </xsl:text>
										</span>
										<xsl:for-each select="onlC:PotrdiloOZadrzanostiOdDela">
											<xsl:for-each select="Podatki">
												<xsl:for-each select="CasZadrzanostiOdDela">
													<xsl:for-each select="SteviloUrDelovneObveznostiNaDan">
														<span style="font-family:Open Sans; font-weight:bold; ">
															<xsl:variable name="altova:seqContentStrings_18">
																<xsl:value-of select="format-number(number(string(.)), '##0,00', 'format1')"/>
															</xsl:variable>
															<xsl:variable name="altova:sContent_18" select="string($altova:seqContentStrings_18)"/>
															<xsl:value-of select="$altova:sContent_18"/>
														</span>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
										<span style="font-family:Open Sans; ">
											<xsl:text> ur na dan</xsl:text>
										</span>
										<br/>
										<span style="font-family:Open Sans; ">
											<xsl:text>Od tega zadržan od dela: </xsl:text>
										</span>
										<xsl:for-each select="onlC:PotrdiloOZadrzanostiOdDela">
											<xsl:for-each select="Podatki">
												<xsl:for-each select="CasZadrzanostiOdDela">
													<xsl:for-each select="SteviloUrZadrzanostiNaDan">
														<span style="font-family:Open Sans; font-weight:bold; ">
															<xsl:variable name="altova:seqContentStrings_19">
																<xsl:value-of select="format-number(number(string(.)), '##0,00', 'format1')"/>
															</xsl:variable>
															<xsl:variable name="altova:sContent_19" select="string($altova:seqContentStrings_19)"/>
															<xsl:value-of select="$altova:sContent_19"/>
														</span>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
										<span style="font-family:Open Sans; ">
											<xsl:text>&#160; ur na dan</xsl:text>
										</span>
									</div>
								</td>
							</tr>
						</tbody>
					</table>
					<table style="border-bottom-style:none; border-left-style:none; border-right-style:none; border-top-style:none; " border="1" width="100%">
						<xsl:variable name="altova:CurrContextGrid_20" select="."/>
						<tbody>
							<tr>
								<td style="border-bottom-style:none; border-left-style:none; border-right-style:none; border-top-style:none; width:50%; ">
									<div>
										<span style="color:green; font-family:Open Sans; font-size:8pt; ">
											<xsl:text>11 - RAZLOG ZADRŽANOSTI</xsl:text>
										</span>
										<span style="color:gray; font-family:Open Sans; font-size:8pt; ">
											<xsl:text>&#160;</xsl:text>
										</span>
									</div>
								</td>
								<td style="border-bottom-style:none; border-left-style:none; border-right-style:none; border-top-style:none; width:0.1in; "/>
								<td style="border-bottom-style:none; border-left-style:none; border-right-style:none; border-top-style:none; width:50%; ">
									<div>
										<span style="color:green; font-family:Open Sans; font-size:8pt; ">
											<xsl:text>12 - INVALIDNOST</xsl:text>
										</span>
									</div>
								</td>
							</tr>
							<tr>
								<td style="border-bottom-color:green; border-bottom-style:solid; border-bottom-width:thin; border-left-color:gray; border-left-style:solid; border-left-width:thin; border-right-color:green; border-right-style:solid; border-right-width:thin; border-top-color:green; border-top-style:solid; border-top-width:thin; text-align:left; width:50%; ">
									<div style="padding-left:0.1cm; text-align:left; ">
										<span style="font-family:Open Sans; ">
											<xsl:text>Razlog zadržanosti: </xsl:text>
										</span>
										<xsl:for-each select="onlC:PotrdiloOZadrzanostiOdDela">
											<xsl:for-each select="Podatki">
												<xsl:for-each select="RazlogZadrzanosti">
													<xsl:for-each select="SifraRazlogaZadrzanosti">
														<xsl:if test="@sifra&lt;10">
															<span style="font-family:Open Sans; font-weight:bold; ">
																<xsl:text>0</xsl:text>
															</span>
														</xsl:if>
														<xsl:for-each select="@sifra">
															<span style="font-family:Open Sans; font-weight:bold; ">
																<xsl:value-of select="string(.)"/>
															</span>
														</xsl:for-each>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
										<span style="font-family:Open Sans; ">
											<xsl:text>&#160;</xsl:text>
										</span>
										<xsl:choose>
											<xsl:when test="onlC:PotrdiloOZadrzanostiOdDela/Podatki/RazlogZadrzanosti/SifraRazlogaZadrzanosti/@sifra=1">
												<span style="font-family:Open Sans; font-weight:bold; ">
													<xsl:text>BOLEZEN</xsl:text>
												</span>
											</xsl:when>
											<xsl:when test="onlC:PotrdiloOZadrzanostiOdDela/Podatki/RazlogZadrzanosti/SifraRazlogaZadrzanosti/@sifra=2">
												<span style="font-family:Open Sans; font-weight:bold; ">
													<xsl:text>POŠKODBA IZVEN DELA</xsl:text>
												</span>
											</xsl:when>
											<xsl:when test="onlC:PotrdiloOZadrzanostiOdDela/Podatki/RazlogZadrzanosti/SifraRazlogaZadrzanosti/@sifra=3">
												<span style="font-family:Open Sans; font-weight:bold; ">
													<xsl:text>POKLICNA BOLEZEN</xsl:text>
												</span>
											</xsl:when>
											<xsl:when test="onlC:PotrdiloOZadrzanostiOdDela/Podatki/RazlogZadrzanosti/SifraRazlogaZadrzanosti/@sifra=4">
												<span style="font-family:Open Sans; font-weight:bold; ">
													<xsl:text>POŠKODBA PRI DELU</xsl:text>
												</span>
											</xsl:when>
											<xsl:when test="onlC:PotrdiloOZadrzanostiOdDela/Podatki/RazlogZadrzanosti/SifraRazlogaZadrzanosti/@sifra=5">
												<span style="font-family:Open Sans; font-weight:bold; ">
													<xsl:text>POŠ.PO TRETJI OSEBI IZVEN DELA</xsl:text>
												</span>
											</xsl:when>
											<xsl:when test="onlC:PotrdiloOZadrzanostiOdDela/Podatki/RazlogZadrzanosti/SifraRazlogaZadrzanosti/@sifra=6">
												<span style="font-family:Open Sans; font-weight:bold; ">
													<xsl:text>NEGA</xsl:text>
												</span>
											</xsl:when>
											<xsl:when test="onlC:PotrdiloOZadrzanostiOdDela/Podatki/RazlogZadrzanosti/SifraRazlogaZadrzanosti/@sifra=7">
												<span style="font-family:Open Sans; font-weight:bold; ">
													<xsl:text>TRANSPLANTACIJA</xsl:text>
												</span>
											</xsl:when>
											<xsl:when test="onlC:PotrdiloOZadrzanostiOdDela/Podatki/RazlogZadrzanosti/SifraRazlogaZadrzanosti/@sifra=8">
												<span style="font-family:Open Sans; font-weight:bold; ">
													<xsl:text>IZOLACIJA</xsl:text>
												</span>
											</xsl:when>
											<xsl:when test="onlC:PotrdiloOZadrzanostiOdDela/Podatki/RazlogZadrzanosti/SifraRazlogaZadrzanosti/@sifra=9">
												<span style="font-family:Open Sans; font-weight:bold; ">
													<xsl:text>SPREMSTVO</xsl:text>
												</span>
											</xsl:when>
											<xsl:when test="onlC:PotrdiloOZadrzanostiOdDela/Podatki/RazlogZadrzanosti/SifraRazlogaZadrzanosti/@sifra=10">
												<span style="font-family:Open Sans; font-weight:bold; ">
													<xsl:text>USPOSABLJANJE ZA REHABILITACIJO OTROKA</xsl:text>
												</span>
											</xsl:when>
											<xsl:when test="onlC:PotrdiloOZadrzanostiOdDela/Podatki/RazlogZadrzanosti/SifraRazlogaZadrzanosti/@sifra=11">
												<span style="font-family:Open Sans; font-weight:bold; ">
													<xsl:text>POŠKODBA NASTALA PRI AKTIVNOSTIH IZ 18.ČLENA ZAKONA</xsl:text>
												</span>
											</xsl:when>
										</xsl:choose>
										<br/>
										<span style="font-family:Open Sans; ">
											<xsl:text>Prvi dan zadržanosti za razlog: </xsl:text>
										</span>
										<xsl:for-each select="onlC:PotrdiloOZadrzanostiOdDela">
											<xsl:for-each select="Podatki">
												<xsl:for-each select="RazlogZadrzanosti">
													<xsl:for-each select="DatumPrvegaDneZadrzanostiZaRazlog">
														<span style="font-family:Open Sans; font-weight:bold; ">
															<xsl:variable name="altova:seqContentStrings_21">
																<xsl:value-of select="format-number(number(substring(string(string(.)), 9, 2)), '00', 'format1')"/>
																<xsl:text>. </xsl:text>
																<xsl:value-of select="format-number(number(substring(string(string(.)), 6, 2)), '00', 'format1')"/>
																<xsl:text>. </xsl:text>
																<xsl:value-of select="format-number(number(substring(string(string(string(.))), 1, 4)), '0000', 'format1')"/>
															</xsl:variable>
															<xsl:variable name="altova:sContent_21" select="string($altova:seqContentStrings_21)"/>
															<xsl:value-of select="$altova:sContent_21"/>
														</span>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
									</div>
								</td>
								<td style="border-bottom-color:green; border-bottom-style:none; border-bottom-width:thin; border-left-color:gray; border-left-style:none; border-left-width:thin; border-right-color:green; border-right-style:none; border-right-width:thin; border-top-color:green; border-top-style:none; border-top-width:thin; width:0.1in; "/>
								<td style="border-bottom-color:green; border-bottom-style:solid; border-bottom-width:thin; border-left-color:gray; border-left-style:solid; border-left-width:thin; border-right-color:green; border-right-style:solid; border-right-width:thin; border-top-color:green; border-top-style:solid; border-top-width:thin; width:50%; ">
									<div style="padding-left:0.1cm; ">
										<span style="font-family:Open Sans; ">
											<xsl:text>Invalid: </xsl:text>
										</span>
										<xsl:for-each select="onlC:PotrdiloOZadrzanostiOdDela">
											<xsl:for-each select="Podatki">
												<xsl:for-each select="KategorijaInvalidnosti">
													<xsl:for-each select="@sifra">
														<span style="font-family:Open Sans; font-weight:bold; ">
															<xsl:value-of select="string(.)"/>
														</span>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
										<span style="font-family:Open Sans; ">
											<xsl:text>&#160; </xsl:text>
										</span>
										<xsl:choose>
											<xsl:when test="onlC:PotrdiloOZadrzanostiOdDela/Podatki/KategorijaInvalidnosti/@sifra=1">
												<span style="font-family:Open Sans; font-weight:bold; ">
													<xsl:text>I.kat.</xsl:text>
												</span>
											</xsl:when>
											<xsl:when test="onlC:PotrdiloOZadrzanostiOdDela/Podatki/KategorijaInvalidnosti/@sifra=2">
												<span style="font-family:Open Sans; font-weight:bold; ">
													<xsl:text>II.kat.</xsl:text>
												</span>
											</xsl:when>
											<xsl:when test="onlC:PotrdiloOZadrzanostiOdDela/Podatki/KategorijaInvalidnosti/@sifra=3">
												<span style="font-family:Open Sans; font-weight:bold; ">
													<xsl:text>III.kat.</xsl:text>
												</span>
											</xsl:when>
										</xsl:choose>
									</div>
								</td>
							</tr>
							<tr>
								<td style="border-bottom-color:green; border-bottom-style:none; border-bottom-width:thin; border-left-color:green; border-left-style:none; border-left-width:thin; border-right-color:green; border-right-style:none; border-right-width:thin; border-top-color:green; border-top-style:none; border-top-width:thin; text-align:justify; width:50%; " valign="bottom">
									<br/>
									<span style="font-family:Open Sans; ">
										<xsl:text>Dne: </xsl:text>
									</span>
									<xsl:for-each select="onlC:PotrdiloOZadrzanostiOdDela">
										<xsl:for-each select="Podatki">
											<xsl:for-each select="DatumIzdajePotrdila">
												<span style="font-family:Open Sans; font-weight:bold; ">
													<xsl:variable name="altova:seqContentStrings_22">
														<xsl:value-of select="format-number(number(substring(string(string(.)), 9, 2)), '00', 'format1')"/>
														<xsl:text>. </xsl:text>
														<xsl:value-of select="format-number(number(substring(string(string(.)), 6, 2)), '00', 'format1')"/>
														<xsl:text>. </xsl:text>
														<xsl:value-of select="format-number(number(substring(string(string(string(.))), 1, 4)), '0000', 'format1')"/>
													</xsl:variable>
													<xsl:variable name="altova:sContent_22" select="string($altova:seqContentStrings_22)"/>
													<xsl:value-of select="$altova:sContent_22"/>
												</span>
											</xsl:for-each>
										</xsl:for-each>
									</xsl:for-each>
									<br/>
									<span style="font-family:Open Sans; ">
										<xsl:text>Kraj: </xsl:text>
									</span>
									<xsl:for-each select="onlC:PotrdiloOZadrzanostiOdDela">
										<xsl:for-each select="Podatki">
											<xsl:for-each select="KrajIzdajePotrdila">
												<span style="font-family:Open Sans; font-weight:bold; ">
													<xsl:apply-templates/>
												</span>
											</xsl:for-each>
										</xsl:for-each>
									</xsl:for-each>
									<br/>
									<br/>
									<span style="color:red; font-family:Open Sans; font-size:12pt; font-weight:bold; ">
										<xsl:text>PREKLICAN</xsl:text>
									</span>
								</td>
								<td style="border-bottom-style:none; border-left-style:none; border-right-style:none; border-top-style:none; width:0.1in; "/>
								<td style="border-bottom-color:green; border-bottom-style:none; border-bottom-width:thin; border-left-color:green; border-left-style:none; border-left-width:thin; border-right-color:green; border-right-style:none; border-right-width:thin; border-top-color:green; border-top-style:none; border-top-width:thin; width:50%; " valign="bottom">
									<br/>
									<span style="font-family:Open Sans; ">
										<xsl:text>Podpisnik: </xsl:text>
									</span>
									<span style="font-family:Open Sans; font-weight:bold; ">
										<xsl:value-of select="translate( substring-before( substring-after( onlC:PotrdiloOZadrzanostiOdDela/Podatki/ds:Signature/ds:KeyInfo/ds:X509Data/ds:X509SubjectName , &apos;CN=&apos;), &apos;,&apos;), &apos;0123456789&apos;,&apos;&apos;)"/>
									</span>
									<br/>
									<span style="font-family:Open Sans; ">
										<xsl:text>Izdajatelj dig.potrdila: </xsl:text>
									</span>
									<xsl:choose>
										<xsl:when test="substring-after( onlC:PotrdiloOZadrzanostiOdDela/Podatki/ds:Signature/ds:KeyInfo/ds:X509Data/ds:X509IssuerSerial/ds:X509IssuerName, &apos;CN=&apos;)">
											<span style="font-family:Open Sans; font-weight:bold; ">
												<xsl:value-of select="substring-before( substring-after( onlC:PotrdiloOZadrzanostiOdDela/Podatki/ds:Signature/ds:KeyInfo/ds:X509Data/ds:X509IssuerSerial/ds:X509IssuerName, &apos;CN=&apos;), &apos;,&apos; )"/>
											</span>
										</xsl:when>
										<xsl:when test="substring-after( onlC:PotrdiloOZadrzanostiOdDela/Podatki/ds:Signature/ds:KeyInfo/ds:X509Data/ds:X509IssuerSerial/ds:X509IssuerName, &apos;OU=&apos;)">
											<span style="font-family:Open Sans; font-weight:bold; ">
												<xsl:value-of select="substring-before( substring-after( onlC:PotrdiloOZadrzanostiOdDela/Podatki/ds:Signature/ds:KeyInfo/ds:X509Data/ds:X509IssuerSerial/ds:X509IssuerName, &apos;OU=&apos;), &apos;,&apos; )"/>
											</span>
										</xsl:when>
										<xsl:when test="substring-after( onlC:PotrdiloOZadrzanostiOdDela/Podatki/ds:Signature/ds:KeyInfo/ds:X509Data/ds:X509IssuerSerial/ds:X509IssuerName, &apos;O=&apos;)">
											<span style="font-family:Open Sans; font-weight:bold; ">
												<xsl:value-of select="substring-before( substring-after( onlC:PotrdiloOZadrzanostiOdDela/Podatki/ds:Signature/ds:KeyInfo/ds:X509Data/ds:X509IssuerSerial/ds:X509IssuerName, &apos;O=&apos;), &apos;,&apos; )"/>
											</span>
										</xsl:when>
									</xsl:choose>
									<br/>
									<span style="font-family:Open Sans; ">
										<xsl:text>Ser.št.dig.pot.: </xsl:text>
									</span>
									<xsl:for-each select="onlC:PotrdiloOZadrzanostiOdDela">
										<xsl:for-each select="Podatki">
											<xsl:for-each select="ds:Signature">
												<xsl:for-each select="ds:KeyInfo">
													<xsl:for-each select="ds:X509Data">
														<xsl:for-each select="ds:X509IssuerSerial">
															<xsl:for-each select="ds:X509SerialNumber">
																<span style="font-family:Open Sans; font-weight:bold; ">
																	<xsl:apply-templates/>
																</span>
															</xsl:for-each>
														</xsl:for-each>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
									</xsl:for-each>
									<span style="font-family:Open Sans; ">
										<xsl:text>&#160; </xsl:text>
									</span>
								</td>
							</tr>
						</tbody>
					</table>
					<br/>
				</xsl:for-each>
			</body>
		</html>
	</xsl:template>
</xsl:stylesheet>
