<?xml version="1.0" encoding="UTF-8"?>
<!--Designed and generated by Altova StyleVision Enterprise Edition 2017 rel. 3 sp1 - see http://www.altova.com/stylevision for more information.-->
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:altova="http://www.altova.com" xmlns:altova-xfi="http://www.altova.com/xslt-extensions/xbrl" xmlns:altovaext="http://www.altova.com/xslt-extensions" xmlns:array="http://www.w3.org/2005/xpath-functions/array" xmlns:clitype="clitype" xmlns:ds="http://www.w3.org/2000/09/xmldsig#" xmlns:fn="http://www.w3.org/2005/xpath-functions" xmlns:iso4217="http://www.xbrl.org/2003/iso4217" xmlns:ix="http://www.xbrl.org/2008/inlineXBRL" xmlns:java="java" xmlns:link="http://www.xbrl.org/2003/linkbase" xmlns:map="http://www.w3.org/2005/xpath-functions/map" xmlns:math="http://www.w3.org/2005/xpath-functions/math" xmlns:nboM="http://zzzs.si/b2b/nbo/0001/DataTypes/nboModriDataType" xmlns:sps="http://www.altova.com/StyleVision/user-xpath-functions" xmlns:xbrldi="http://xbrl.org/2006/xbrldi" xmlns:xbrli="http://www.xbrl.org/2003/instance" xmlns:xenc="http://www.w3.org/2001/04/xmlenc#" xmlns:xff="http://www.xbrl.org/2010/function/formula" xmlns:xfi="http://www.xbrl.org/2008/function/instance" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" exclude-result-prefixes="altova altova-xfi altovaext array clitype ds fn iso4217 ix java link map math nboM sps xbrldi xbrli xenc xff xfi xlink xs xsi">
	<xsl:output version="4.0" method="html" indent="no" encoding="UTF-8" doctype-public="-//W3C//DTD HTML 4.01 Transitional//EN" doctype-system="http://www.w3.org/TR/html4/loose.dtd"/>
	<xsl:param name="SV_OutputFormat" select="'HTML'"/>
	<xsl:variable name="XML" select="/"/>
	<xsl:variable name="altova:nPxPerIn" select="96"/>
	<xsl:decimal-format name="format1" grouping-separator="." decimal-separator=","/>
	<xsl:template match="/">
		<html>
			<head>
				<title/>
				<meta name="generator" content="Altova StyleVision Enterprise Edition 2017 rel. 3 sp1 (http://www.altova.com)"/>
				<meta http-equiv="X-UA-Compatible" content="IE=9"/>
				<xsl:comment>[if IE]&gt;&lt;STYLE type=&quot;text/css&quot;&gt;.altova-rotate-left-textbox{filter: progid:DXImageTransform.Microsoft.BasicImage(rotation=3)} .altova-rotate-right-textbox{filter: progid:DXImageTransform.Microsoft.BasicImage(rotation=1)} &lt;/STYLE&gt;&lt;![endif]</xsl:comment>
				<xsl:comment>[if !IE]&gt;&lt;!</xsl:comment>
				<style type="text/css">.altova-rotate-left-textbox{-webkit-transform: rotate(-90deg) translate(-100%, 0%); -webkit-transform-origin: 0% 0%;-moz-transform: rotate(-90deg) translate(-100%, 0%); -moz-transform-origin: 0% 0%;-ms-transform: rotate(-90deg) translate(-100%, 0%); -ms-transform-origin: 0% 0%;}.altova-rotate-right-textbox{-webkit-transform: rotate(90deg) translate(0%, -100%); -webkit-transform-origin: 0% 0%;-moz-transform: rotate(90deg) translate(0%, -100%); -moz-transform-origin: 0% 0%;-ms-transform: rotate(90deg) translate(0%, -100%); -ms-transform-origin: 0% 0%;}</style>
				<xsl:comment>&lt;![endif]</xsl:comment>
				<style type="text/css">@page { margin-left:2cm; margin-right:2cm; margin-top:2.54cm; margin-bottom:2.2cm } @media print { br.altova-page-break { page-break-before: always; } div.altova-page-break { page-break-before: always; } }</style>
			</head>
			<body style="color:black; font-family:Open Sans; font-size:11px; keep-together:always; ">
				<xsl:for-each select="$XML">
					<xsl:if test="count(nboM:PotrdiloOZadrzanostiOdDela/Podatki/Storno/@sifra)">
						<br/>
						<table style="border-bottom-style:none; border-left-style:none; border-right-style:none; border-top-style:none; font-family:Open Sans; font-size:8pt; " border="1" width="100%">
							<xsl:variable name="altova:CurrContextGrid_0" select="."/>
							<tbody style="font-size:8pt; ">
								<tr>
									<td style="border-bottom-style:none; border-left-style:none; border-right-style:none; border-top-style:none; text-align:right; width:10,33in; ">
										<span style="color:red; font-family:Open Sans; font-size:12pt; font-weight:bold; ">
											<xsl:text>PREKLICAN</xsl:text>
										</span>
										<br/>
									</td>
								</tr>
							</tbody>
						</table>
					</xsl:if>
					<br/>
					<table style="border-bottom-style:none; border-left-style:none; border-right-style:none; border-top-style:none; font-family:Open Sans; font-size:8pt; " border="1" width="100%">
						<xsl:variable name="altova:CurrContextGrid_1" select="."/>
						<tbody style="font-size:8pt; ">
							<tr style="font-size:8pt; ">
								<td style="border-bottom-style:none; border-left-style:none; border-right-style:none; border-top-style:none; font-size:8pt; text-align:left; width:10.31in; ">
									<br/>
									<span style="font-family:Open Sans; font-size:14pt; font-weight:bold; ">
										<xsl:text>POTRDILO O UPRAVIČENI ZADRŽANOSTI OD DELA&#160; ŠT. </xsl:text>
									</span>
									<xsl:for-each select="nboM:PotrdiloOZadrzanostiOdDela">
										<xsl:for-each select="Podatki">
											<xsl:for-each select="StevilkaPotrdilaOZadrzanostiOdDela">
												<span style="font-family:Open Sans; font-size:14pt; font-weight:bold; ">
													<xsl:apply-templates/>
												</span>
											</xsl:for-each>
										</xsl:for-each>
									</xsl:for-each>
									<br/>
									<br/>
								</td>
							</tr>
						</tbody>
					</table>
					<table style="font-family:Open Sans; font-size:11pt; " border="0" width="100%">
						<xsl:variable name="altova:CurrContextGrid_2" select="."/>
						<tbody>
							<tr>
								<td style="text-align:left; width:10,40in; ">
									<table style="border-bottom-style:none; border-left-style:none; border-right-style:none; border-top-style:none; font-family:Open Sans; font-size:8pt; " border="1" width="100%">
										<xsl:variable name="altova:CurrContextGrid_3" select="."/>
										<tbody style="font-weight:normal; ">
											<tr>
												<td style="border-bottom-color:blue; border-bottom-style:none; border-left-color:blue; border-left-style:none; border-right-color:blue; border-right-style:none; border-top-color:blue; border-top-style:none; text-align:left; width:50%; " valign="middle">
													<div style="text-align:left; ">
														<span style="color:#4472C4; font-family:Open Sans; font-size:8pt; ">
															<xsl:text>1 - ZAVAROVANA OSEBA</xsl:text>
														</span>
													</div>
												</td>
												<td style="border-bottom-color:blue; border-bottom-style:none; border-left-color:blue; border-left-style:none; border-right-color:blue; border-right-style:none; border-top-color:blue; border-top-style:none; text-align:left; width:0.1in; "/>
												<td style="border-bottom-color:blue; border-bottom-style:none; border-left-color:blue; border-left-style:none; border-right-color:blue; border-right-style:none; border-top-color:blue; border-top-style:none; text-align:left; width:50%; " valign="middle">
													<div style="text-align:left; ">
														<span style="color:#4472C4; font-family:Open Sans; font-size:8pt; ">
															<xsl:text>2 - ZAVEZANEC</xsl:text>
														</span>
													</div>
												</td>
											</tr>
											<tr>
												<td style="border-bottom-color:blue; border-bottom-style:solid; border-bottom-width:thin; border-left-color:blue; border-left-style:solid; border-left-width:thin; border-right-color:blue; border-right-style:solid; border-right-width:thin; border-top-color:blue; border-top-style:solid; border-top-width:thin; font-weight:normal; text-align:left; width:50%; ">
													<table style="border-collapse:collapse; font-family:Open Sans; font-size:10pt; font-weight:normal; " bgcolor="white" border="0">
														<xsl:variable name="altova:CurrContextGrid_4" select="."/>
														<tbody style="font-weight:normal; ">
															<tr style="font-weight:normal; ">
																<xsl:for-each select="nboM:PotrdiloOZadrzanostiOdDela">
																	<xsl:for-each select="Podatki">
																		<xsl:for-each select="ZavarovanaOseba">
																			<td style="text-align:left; ">
																				<span style="font-family:Open Sans; font-size:10pt; text-align:right; ">
																					<xsl:text>Številka: </xsl:text>
																				</span>
																				<xsl:for-each select="ZZZSStevilka">
																					<span style="font-family:Open Sans; font-weight:bold; ">
																						<xsl:apply-templates/>
																					</span>
																				</xsl:for-each>
																			</td>
																		</xsl:for-each>
																	</xsl:for-each>
																</xsl:for-each>
															</tr>
															<tr>
																<xsl:for-each select="nboM:PotrdiloOZadrzanostiOdDela">
																	<xsl:for-each select="Podatki">
																		<xsl:for-each select="ZavarovanaOseba">
																			<td>
																				<span style="font-family:Open Sans; font-size:10pt; ">
																					<xsl:text>Priimek in ime:</xsl:text>
																				</span>
																				<span style="font-size:10pt; ">
																					<xsl:text>&#160;</xsl:text>
																				</span>
																				<xsl:for-each select="ImeOsebe">
																					<xsl:for-each select="Priimek1">
																						<span style="font-family:Open Sans; font-weight:bold; ">
																							<xsl:apply-templates/>
																						</span>
																					</xsl:for-each>
																				</xsl:for-each>
																				<xsl:if test="not(ImeOsebe/PriimekVezaj)">
																					<span>
																						<xsl:text>&#160;</xsl:text>
																					</span>
																				</xsl:if>
																				<xsl:for-each select="ImeOsebe">
																					<xsl:for-each select="PriimekVezaj">
																						<span style="font-family:Open Sans; font-weight:bold; ">
																							<xsl:apply-templates/>
																						</span>
																					</xsl:for-each>
																				</xsl:for-each>
																				<xsl:for-each select="ImeOsebe">
																					<xsl:for-each select="Priimek2">
																						<span style="font-family:Open Sans; font-weight:bold; ">
																							<xsl:apply-templates/>
																						</span>
																					</xsl:for-each>
																				</xsl:for-each>
																				<xsl:choose>
																					<xsl:when test="not(ImeOsebe/Priimek2)"/>
																					<xsl:when test="(ImeOsebe/Priimek2)">
																						<span>
																							<xsl:text>&#160;</xsl:text>
																						</span>
																					</xsl:when>
																				</xsl:choose>
																				<xsl:for-each select="ImeOsebe">
																					<xsl:for-each select="Ime1">
																						<span style="font-family:Open Sans; font-weight:bold; ">
																							<xsl:apply-templates/>
																						</span>
																					</xsl:for-each>
																				</xsl:for-each>
																				<xsl:choose>
																					<xsl:when test="not(ImeOsebe/ImeVezaj)">
																						<span>
																							<xsl:text>&#160;</xsl:text>
																						</span>
																					</xsl:when>
																					<xsl:when test="ImeOsebe/ImeVezaj"/>
																				</xsl:choose>
																				<xsl:for-each select="ImeOsebe">
																					<xsl:for-each select="ImeVezaj">
																						<span style="font-family:Open Sans; font-weight:bold; ">
																							<xsl:apply-templates/>
																						</span>
																					</xsl:for-each>
																				</xsl:for-each>
																				<xsl:for-each select="ImeOsebe">
																					<xsl:for-each select="Ime2">
																						<span style="font-family:Open Sans; font-weight:bold; ">
																							<xsl:apply-templates/>
																						</span>
																					</xsl:for-each>
																				</xsl:for-each>
																			</td>
																		</xsl:for-each>
																	</xsl:for-each>
																</xsl:for-each>
															</tr>
															<tr>
																<xsl:for-each select="nboM:PotrdiloOZadrzanostiOdDela">
																	<xsl:for-each select="Podatki">
																		<xsl:for-each select="ZavarovanaOseba">
																			<td style="text-align:left; ">
																				<span style="font-family:Open Sans; font-size:10pt; ">
																					<xsl:text>Zavarovalna podlaga:</xsl:text>
																				</span>
																				<span style="font-size:10pt; ">
																					<xsl:text>&#160;</xsl:text>
																				</span>
																				<xsl:for-each select="SifraZavarovalnePodlageIzOZZ">
																					<xsl:for-each select="@sifra">
																						<span style="font-family:Open Sans; font-weight:bold; ">
																							<xsl:value-of select="string(.)"/>
																						</span>
																					</xsl:for-each>
																				</xsl:for-each>
																			</td>
																		</xsl:for-each>
																	</xsl:for-each>
																</xsl:for-each>
															</tr>
															<tr>
																<xsl:for-each select="nboM:PotrdiloOZadrzanostiOdDela">
																	<xsl:for-each select="Podatki">
																		<xsl:for-each select="ZavarovanaOseba">
																			<td style="text-align:left; ">
																				<span style="font-family:Open Sans; font-size:10pt; ">
																					<xsl:text>Enota ZZZS zavarovanja:</xsl:text>
																				</span>
																				<span style="font-size:10pt; ">
																					<xsl:text>&#160;</xsl:text>
																				</span>
																				<xsl:for-each select="SifraIzpostaveLokacijeZaposlitve">
																					<xsl:for-each select="@sifra">
																						<span style="font-family:Open Sans; font-weight:bold; ">
																							<xsl:value-of select="string(.)"/>
																						</span>
																					</xsl:for-each>
																				</xsl:for-each>
																			</td>
																		</xsl:for-each>
																	</xsl:for-each>
																</xsl:for-each>
															</tr>
														</tbody>
													</table>
												</td>
												<td style="border-bottom-color:blue; border-bottom-style:none; border-left-color:blue; border-left-style:none; border-right-color:blue; border-right-style:none; border-top-color:blue; border-top-style:none; text-align:left; width:0.1in; "/>
												<td style="border-bottom-color:blue; border-bottom-style:solid; border-bottom-width:thin; border-left-color:blue; border-left-style:solid; border-left-width:thin; border-right-color:blue; border-right-style:solid; border-right-width:thin; border-top-color:blue; border-top-style:solid; border-top-width:thin; font-weight:normal; text-align:left; width:50%; " valign="top">
													<table style="border-collapse:collapse; font-family:Open Sans; font-size:10pt; " bgcolor="white" border="0">
														<xsl:variable name="altova:CurrContextGrid_5" select="."/>
														<tbody>
															<tr>
																<xsl:for-each select="nboM:PotrdiloOZadrzanostiOdDela">
																	<xsl:for-each select="Podatki">
																		<xsl:for-each select="Zavezanec">
																			<td style="text-align:left; ">
																				<span style="font-family:Open Sans; font-size:10pt; ">
																					<xsl:text>Registrska št.:</xsl:text>
																				</span>
																				<span style="font-size:10pt; ">
																					<xsl:text>&#160;</xsl:text>
																				</span>
																				<xsl:for-each select="RegistrskaStevilka">
																					<span style="font-family:Open Sans; font-weight:bold; ">
																						<xsl:apply-templates/>
																					</span>
																				</xsl:for-each>
																			</td>
																		</xsl:for-each>
																	</xsl:for-each>
																</xsl:for-each>
															</tr>
															<tr>
																<xsl:for-each select="nboM:PotrdiloOZadrzanostiOdDela">
																	<xsl:for-each select="Podatki">
																		<xsl:for-each select="Zavezanec">
																			<td style="text-align:left; ">
																				<span style="font-family:Open Sans; font-size:10pt; ">
																					<xsl:text>Zap.št.potrdila: </xsl:text>
																				</span>
																				<xsl:for-each select="ZaporednaStevilkaPotrdila">
																					<span style="font-family:Open Sans; font-weight:bold; ">
																						<xsl:apply-templates/>
																					</span>
																				</xsl:for-each>
																			</td>
																		</xsl:for-each>
																	</xsl:for-each>
																</xsl:for-each>
															</tr>
															<tr>
																<xsl:for-each select="nboM:PotrdiloOZadrzanostiOdDela">
																	<xsl:for-each select="Podatki">
																		<xsl:for-each select="Zavezanec">
																			<td style="text-align:left; ">
																				<span style="font-family:Open Sans; font-size:10pt; ">
																					<xsl:text>Naziv:</xsl:text>
																				</span>
																				<span style="font-size:10pt; ">
																					<xsl:text>&#160;</xsl:text>
																				</span>
																				<xsl:for-each select="NazivZavezanca">
																					<span style="font-family:Open Sans; font-weight:bold; ">
																						<xsl:apply-templates/>
																					</span>
																				</xsl:for-each>
																			</td>
																		</xsl:for-each>
																	</xsl:for-each>
																</xsl:for-each>
															</tr>
															<tr>
																<xsl:for-each select="nboM:PotrdiloOZadrzanostiOdDela">
																	<xsl:for-each select="Podatki">
																		<xsl:for-each select="Zavezanec">
																			<td style="text-align:left; ">
																				<span style="font-family:Open Sans; font-size:10pt; ">
																					<xsl:text>Šifra dejavnosti:</xsl:text>
																				</span>
																				<span style="font-size:10pt; ">
																					<xsl:text>&#160;</xsl:text>
																				</span>
																				<xsl:for-each select="SifraDejavnosti">
																					<xsl:for-each select="@sifra">
																						<span style="font-family:Open Sans; font-weight:bold; ">
																							<xsl:value-of select="string(.)"/>
																						</span>
																					</xsl:for-each>
																				</xsl:for-each>
																			</td>
																		</xsl:for-each>
																	</xsl:for-each>
																</xsl:for-each>
															</tr>
														</tbody>
													</table>
												</td>
											</tr>
										</tbody>
									</table>
									<table style="border-bottom-style:none; border-left-style:none; border-right-style:none; border-top-style:none; font-family:Open Sans; font-size:8pt; " border="1" width="100%">
										<xsl:variable name="altova:CurrContextGrid_6" select="."/>
										<tbody style="font-weight:normal; ">
											<tr>
												<td style="border-bottom-color:blue; border-bottom-style:none; border-left-color:blue; border-left-style:none; border-right-color:blue; border-right-style:none; border-top-color:blue; border-top-style:none; text-align:left; width:50%; " valign="middle">
													<div style="text-align:left; ">
														<span style="color:#4472C4; font-family:Open Sans; font-size:8pt; ">
															<xsl:text>3 - RAZLOG ZADRŽANOSTI</xsl:text>
														</span>
													</div>
												</td>
												<td style="border-bottom-color:blue; border-bottom-style:none; border-left-color:blue; border-left-style:none; border-right-color:blue; border-right-style:none; border-top-color:blue; border-top-style:none; text-align:left; width:0.1in; "/>
												<td style="border-bottom-color:blue; border-bottom-style:none; border-left-color:blue; border-left-style:none; border-right-color:blue; border-right-style:none; border-top-color:blue; border-top-style:none; text-align:left; width:50%; " valign="middle">
													<div style="text-align:left; ">
														<span style="color:#4472C4; font-family:Open Sans; font-size:8pt; ">
															<xsl:text>4 - ZADRŽANOST OD DELA</xsl:text>
														</span>
													</div>
												</td>
											</tr>
											<tr>
												<td style="border-bottom-color:blue; border-bottom-style:solid; border-bottom-width:thin; border-left-color:blue; border-left-style:solid; border-left-width:thin; border-right-color:blue; border-right-style:solid; border-right-width:thin; border-top-color:blue; border-top-style:solid; border-top-width:thin; font-weight:normal; text-align:left; width:50%; " valign="middle">
													<table style="border-collapse:collapse; font-family:Open Sans; font-size:10pt; " bgcolor="white" border="0">
														<xsl:variable name="altova:CurrContextGrid_7" select="."/>
														<tbody>
															<tr>
																<xsl:for-each select="nboM:PotrdiloOZadrzanostiOdDela">
																	<xsl:for-each select="Podatki">
																		<xsl:for-each select="RazlogZadrzanosti">
																			<td style="text-align:left; ">
																				<span style="font-family:Open Sans; font-size:10pt; ">
																					<xsl:text>Razlog zadržanosti: </xsl:text>
																				</span>
																				<xsl:for-each select="SifraRazlogaZadrzanosti">
																					<xsl:if test="@sifra&lt;10">
																						<span style="font-family:Open Sans; font-size:10pt; font-weight:bold; ">
																							<xsl:text>0</xsl:text>
																						</span>
																					</xsl:if>
																					<xsl:for-each select="@sifra">
																						<span style="font-family:Open Sans; font-weight:bold; ">
																							<xsl:value-of select="string(.)"/>
																						</span>
																					</xsl:for-each>
																				</xsl:for-each>
																				<xsl:choose>
																					<xsl:when test="/nboM:PotrdiloOZadrzanostiOdDela/Podatki/RazlogZadrzanosti/SifraRazlogaZadrzanosti/@sifra=1">
																						<span style="font-family:Open Sans; font-size:10pt; font-weight:bold; ">
																							<xsl:text> BOLEZEN</xsl:text>
																						</span>
																					</xsl:when>
																					<xsl:when test="/nboM:PotrdiloOZadrzanostiOdDela/Podatki/RazlogZadrzanosti/SifraRazlogaZadrzanosti/@sifra=2">
																						<span style="font-family:Open Sans; font-size:10pt; font-weight:bold; ">
																							<xsl:text> POŠKODBA IZVEN DELA</xsl:text>
																						</span>
																					</xsl:when>
																					<xsl:when test="/nboM:PotrdiloOZadrzanostiOdDela/Podatki/RazlogZadrzanosti/SifraRazlogaZadrzanosti/@sifra=3">
																						<span style="font-family:Open Sans; font-size:10pt; font-weight:bold; ">
																							<xsl:text> POKLICNA BOLEZEN</xsl:text>
																						</span>
																					</xsl:when>
																					<xsl:when test="/nboM:PotrdiloOZadrzanostiOdDela/Podatki/RazlogZadrzanosti/SifraRazlogaZadrzanosti/@sifra=4">
																						<span style="font-family:Open Sans; font-size:10pt; font-weight:bold; ">
																							<xsl:text> POŠKODBA PRI DELU</xsl:text>
																						</span>
																					</xsl:when>
																					<xsl:when test="/nboM:PotrdiloOZadrzanostiOdDela/Podatki/RazlogZadrzanosti/SifraRazlogaZadrzanosti/@sifra=5">
																						<span style="font-family:Open Sans; font-size:10pt; font-weight:bold; ">
																							<xsl:text> POŠ.PO TRETJI OSEBI IZVEN DELA</xsl:text>
																						</span>
																					</xsl:when>
																					<xsl:when test="/nboM:PotrdiloOZadrzanostiOdDela/Podatki/RazlogZadrzanosti/SifraRazlogaZadrzanosti/@sifra=6">
																						<span style="font-family:Open Sans; font-size:10pt; font-weight:bold; ">
																							<xsl:text> NEGA</xsl:text>
																						</span>
																					</xsl:when>
																					<xsl:when test="/nboM:PotrdiloOZadrzanostiOdDela/Podatki/RazlogZadrzanosti/SifraRazlogaZadrzanosti/@sifra=7">
																						<span style="font-family:Open Sans; font-size:10pt; font-weight:bold; ">
																							<xsl:text> TRANSPLANTACIJA</xsl:text>
																						</span>
																					</xsl:when>
																					<xsl:when test="/nboM:PotrdiloOZadrzanostiOdDela/Podatki/RazlogZadrzanosti/SifraRazlogaZadrzanosti/@sifra=8">
																						<span style="font-family:Open Sans; font-size:10pt; font-weight:bold; ">
																							<xsl:text> IZOLACIJA</xsl:text>
																						</span>
																					</xsl:when>
																					<xsl:when test="/nboM:PotrdiloOZadrzanostiOdDela/Podatki/RazlogZadrzanosti/SifraRazlogaZadrzanosti/@sifra=9">
																						<span style="font-family:Open Sans; font-size:10pt; font-weight:bold; ">
																							<xsl:text> SPREMSTVO</xsl:text>
																						</span>
																					</xsl:when>
																					<xsl:when test="/nboM:PotrdiloOZadrzanostiOdDela/Podatki/RazlogZadrzanosti/SifraRazlogaZadrzanosti/@sifra=10">
																						<span style="font-family:Open Sans; font-size:10pt; font-weight:bold; ">
																							<xsl:text> USPOSABLJANJE ZA REHABILITACIJO OTROKA</xsl:text>
																						</span>
																					</xsl:when>
																					<xsl:when test="/nboM:PotrdiloOZadrzanostiOdDela/Podatki/RazlogZadrzanosti/SifraRazlogaZadrzanosti/@sifra=11">
																						<span style="font-family:Open Sans; font-size:10pt; font-weight:bold; ">
																							<xsl:text> POŠKODBA NASTALA PRI AKTIVNOSTIH IZ 18.ČLENA ZAKONA</xsl:text>
																						</span>
																					</xsl:when>
																				</xsl:choose>
																			</td>
																		</xsl:for-each>
																	</xsl:for-each>
																</xsl:for-each>
															</tr>
															<tr>
																<xsl:for-each select="nboM:PotrdiloOZadrzanostiOdDela">
																	<xsl:for-each select="Podatki">
																		<xsl:for-each select="RazlogZadrzanosti">
																			<td style="text-align:left; ">
																				<span style="font-family:Open Sans; font-size:10pt; ">
																					<xsl:text>Prvi dan zadržanosti za razlog:</xsl:text>
																				</span>
																				<span style="font-size:10pt; ">
																					<xsl:text>&#160;</xsl:text>
																				</span>
																				<xsl:for-each select="DatumPrvegaDneZadrzanostiZaRazlog">
																					<span style="font-family:Open Sans; font-weight:bold; ">
																						<xsl:variable name="altova:seqContentStrings_8">
																							<xsl:value-of select="format-number(number(substring(string(string(.)), 9, 2)), '00', 'format1')"/>
																							<xsl:text>.</xsl:text>
																							<xsl:value-of select="format-number(number(substring(string(string(.)), 6, 2)), '00', 'format1')"/>
																							<xsl:text>.</xsl:text>
																							<xsl:value-of select="format-number(number(substring(string(string(string(.))), 1, 4)), '0000', 'format1')"/>
																						</xsl:variable>
																						<xsl:variable name="altova:sContent_8" select="string($altova:seqContentStrings_8)"/>
																						<xsl:value-of select="$altova:sContent_8"/>
																					</span>
																				</xsl:for-each>
																			</td>
																		</xsl:for-each>
																	</xsl:for-each>
																</xsl:for-each>
															</tr>
														</tbody>
													</table>
													<br/>
												</td>
												<td style="border-bottom-color:blue; border-bottom-style:none; border-left-color:blue; border-left-style:none; border-right-color:blue; border-right-style:none; border-top-color:blue; border-top-style:none; text-align:left; width:0.1in; "/>
												<td style="border-bottom-color:blue; border-bottom-style:solid; border-bottom-width:thin; border-left-color:blue; border-left-style:solid; border-left-width:thin; border-right-color:blue; border-right-style:solid; border-right-width:thin; border-top-color:blue; border-top-style:solid; border-top-width:thin; font-weight:normal; text-align:left; width:50%; " valign="top">
													<table style="font-family:Open Sans; font-size:10pt; " bgcolor="white" border="0">
														<xsl:variable name="altova:CurrContextGrid_9" select="."/>
														<tbody>
															<tr>
																<xsl:for-each select="nboM:PotrdiloOZadrzanostiOdDela">
																	<xsl:for-each select="Podatki">
																		<xsl:for-each select="CasZadrzanostiOdDela">
																			<td style="text-align:left; ">
																				<span style="font-family:Open Sans; ">
																					<xsl:text>Polni delovni čas od:</xsl:text>
																				</span>
																				<span>
																					<xsl:text>&#160;</xsl:text>
																				</span>
																				<xsl:for-each select="ZadrzanostZaPolniDelovniCas">
																					<xsl:for-each select="DatumOd">
																						<span style="font-family:Open Sans; font-weight:bold; ">
																							<xsl:variable name="altova:seqContentStrings_10">
																								<xsl:value-of select="format-number(number(substring(string(string(.)), 9, 2)), '00', 'format1')"/>
																								<xsl:text>.</xsl:text>
																								<xsl:value-of select="format-number(number(substring(string(string(.)), 6, 2)), '00', 'format1')"/>
																								<xsl:text>.</xsl:text>
																								<xsl:value-of select="format-number(number(substring(string(string(string(.))), 1, 4)), '0000', 'format1')"/>
																							</xsl:variable>
																							<xsl:variable name="altova:sContent_10" select="string($altova:seqContentStrings_10)"/>
																							<xsl:value-of select="$altova:sContent_10"/>
																						</span>
																					</xsl:for-each>
																				</xsl:for-each>
																				<span style="font-family:Open Sans; ">
																					<xsl:text> do:</xsl:text>
																				</span>
																				<xsl:for-each select="ZadrzanostZaPolniDelovniCas">
																					<xsl:for-each select="DatumDo">
																						<span style="font-family:Open Sans; font-weight:bold; ">
																							<xsl:variable name="altova:seqContentStrings_11">
																								<xsl:value-of select="format-number(number(substring(string(string(.)), 9, 2)), '00', 'format1')"/>
																								<xsl:text>.</xsl:text>
																								<xsl:value-of select="format-number(number(substring(string(string(.)), 6, 2)), '00', 'format1')"/>
																								<xsl:text>.</xsl:text>
																								<xsl:value-of select="format-number(number(substring(string(string(string(.))), 1, 4)), '0000', 'format1')"/>
																							</xsl:variable>
																							<xsl:variable name="altova:sContent_11" select="string($altova:seqContentStrings_11)"/>
																							<xsl:value-of select="$altova:sContent_11"/>
																						</span>
																					</xsl:for-each>
																				</xsl:for-each>
																			</td>
																		</xsl:for-each>
																	</xsl:for-each>
																</xsl:for-each>
															</tr>
															<tr>
																<xsl:for-each select="nboM:PotrdiloOZadrzanostiOdDela">
																	<xsl:for-each select="Podatki">
																		<xsl:for-each select="CasZadrzanostiOdDela">
																			<td style="text-align:left; ">
																				<span style="font-family:Open Sans; ">
																					<xsl:text>Krajši delovni čas&#160; od:</xsl:text>
																				</span>
																				<span>
																					<xsl:text>&#160;</xsl:text>
																				</span>
																				<xsl:for-each select="ZadrzanostZaKrajsiDelovniCas">
																					<xsl:for-each select="DatumOd">
																						<span style="font-family:Open Sans; font-weight:bold; ">
																							<xsl:variable name="altova:seqContentStrings_12">
																								<xsl:value-of select="format-number(number(substring(string(string(.)), 9, 2)), '00', 'format1')"/>
																								<xsl:text>. </xsl:text>
																								<xsl:value-of select="format-number(number(substring(string(string(.)), 6, 2)), '00', 'format1')"/>
																								<xsl:text>. </xsl:text>
																								<xsl:value-of select="format-number(number(substring(string(string(string(.))), 1, 4)), '0000', 'format1')"/>
																							</xsl:variable>
																							<xsl:variable name="altova:sContent_12" select="string($altova:seqContentStrings_12)"/>
																							<xsl:value-of select="$altova:sContent_12"/>
																						</span>
																					</xsl:for-each>
																				</xsl:for-each>
																				<span style="font-family:Open Sans; ">
																					<xsl:text> do:</xsl:text>
																				</span>
																				<xsl:for-each select="ZadrzanostZaKrajsiDelovniCas">
																					<xsl:for-each select="DatumDo">
																						<span style="font-family:Open Sans; font-weight:bold; ">
																							<xsl:variable name="altova:seqContentStrings_13">
																								<xsl:value-of select="format-number(number(substring(string(string(.)), 9, 2)), '00', 'format1')"/>
																								<xsl:text>. </xsl:text>
																								<xsl:value-of select="format-number(number(substring(string(string(.)), 6, 2)), '00', 'format1')"/>
																								<xsl:text>. </xsl:text>
																								<xsl:value-of select="format-number(number(substring(string(string(string(.))), 1, 4)), '0000', 'format1')"/>
																							</xsl:variable>
																							<xsl:variable name="altova:sContent_13" select="string($altova:seqContentStrings_13)"/>
																							<xsl:value-of select="$altova:sContent_13"/>
																						</span>
																					</xsl:for-each>
																				</xsl:for-each>
																			</td>
																		</xsl:for-each>
																	</xsl:for-each>
																</xsl:for-each>
															</tr>
															<tr>
																<xsl:for-each select="nboM:PotrdiloOZadrzanostiOdDela">
																	<xsl:for-each select="Podatki">
																		<xsl:for-each select="CasZadrzanostiOdDela">
																			<td style="text-align:left; ">
																				<span style="font-family:Open Sans; ">
																					<xsl:text>Dolžan delati:</xsl:text>
																				</span>
																				<span style="font-family:Open Sans; font-weight:bold; ">
																					<xsl:text>&#160;</xsl:text>
																				</span>
																				<xsl:for-each select="SteviloUrDelovneObveznostiNaDan">
																					<span style="font-weight:bold; ">
																						<xsl:variable name="altova:seqContentStrings_14">
																							<xsl:value-of select="format-number(number(string(.)), '##0,00', 'format1')"/>
																						</xsl:variable>
																						<xsl:variable name="altova:sContent_14" select="string($altova:seqContentStrings_14)"/>
																						<xsl:value-of select="$altova:sContent_14"/>
																					</span>
																				</xsl:for-each>
																				<span style="font-family:Open Sans; ">
																					<xsl:text> ur na dan</xsl:text>
																				</span>
																			</td>
																		</xsl:for-each>
																	</xsl:for-each>
																</xsl:for-each>
															</tr>
															<tr>
																<xsl:for-each select="nboM:PotrdiloOZadrzanostiOdDela">
																	<xsl:for-each select="Podatki">
																		<xsl:for-each select="CasZadrzanostiOdDela">
																			<td style="text-align:left; ">
																				<span style="font-family:Open Sans; ">
																					<xsl:text>Od tega zadržan od dela: </xsl:text>
																				</span>
																				<xsl:for-each select="SteviloUrZadrzanostiNaDan">
																					<span style="font-weight:bold; ">
																						<xsl:variable name="altova:seqContentStrings_15">
																							<xsl:value-of select="format-number(number(string(.)), '##0,00', 'format1')"/>
																						</xsl:variable>
																						<xsl:variable name="altova:sContent_15" select="string($altova:seqContentStrings_15)"/>
																						<xsl:value-of select="$altova:sContent_15"/>
																					</span>
																				</xsl:for-each>
																				<span style="font-family:Open Sans; ">
																					<xsl:text> ur na dan</xsl:text>
																				</span>
																			</td>
																		</xsl:for-each>
																	</xsl:for-each>
																</xsl:for-each>
															</tr>
														</tbody>
													</table>
												</td>
											</tr>
										</tbody>
									</table>
									<table style="border-bottom-style:none; border-left-style:none; border-right-style:none; border-top-style:none; font-family:Open Sans; font-size:8pt; " border="1" width="100%">
										<xsl:variable name="altova:CurrContextGrid_16" select="."/>
										<tbody style="font-weight:normal; ">
											<tr>
												<td style="border-bottom-color:blue; border-bottom-style:none; border-left-color:blue; border-left-style:none; border-right-color:blue; border-right-style:none; border-top-color:blue; border-top-style:none; text-align:left; width:50%; " valign="middle">
													<div style="text-align:left; ">
														<span style="color:#4472C4; font-family:Open Sans; font-size:8pt; ">
															<xsl:text>5 -ZADNJI DAN ZADRŽANOSTI</xsl:text>
														</span>
													</div>
												</td>
												<td style="border-bottom-color:blue; border-bottom-style:none; border-left-color:blue; border-left-style:none; border-right-color:blue; border-right-style:none; border-top-color:blue; border-top-style:none; text-align:left; width:0.1in; "/>
												<td style="border-bottom-color:blue; border-bottom-style:none; border-left-color:blue; border-left-style:none; border-right-color:blue; border-right-style:none; border-top-color:blue; border-top-style:none; text-align:left; width:50%; " valign="middle">
													<div style="text-align:left; ">
														<span style="color:#4472C4; font-family:Open Sans; font-size:8pt; ">
															<xsl:text>6 - PRVI DAN ZADRŽANOSTI</xsl:text>
														</span>
													</div>
												</td>
											</tr>
											<tr>
												<td style="border-bottom-color:blue; border-bottom-style:solid; border-bottom-width:thin; border-left-color:blue; border-left-style:solid; border-left-width:thin; border-right-color:blue; border-right-style:solid; border-right-width:thin; border-top-color:blue; border-top-style:solid; border-top-width:thin; font-weight:normal; text-align:left; width:50%; " valign="middle">
													<table style="font-family:Open Sans; font-size:10pt; " border="0" width="100%">
														<xsl:variable name="altova:CurrContextGrid_17" select="."/>
														<tbody>
															<tr>
																<td style="text-align:center; ">
																	<span style="font-family:Open Sans; ">
																		<xsl:text>Za diagnozo:&#160; </xsl:text>
																	</span>
																</td>
																<td style="text-align:center; ">
																	<span style="font-family:Open Sans; ">
																		<xsl:text>Za razlog:&#160;&#160;&#160; </xsl:text>
																	</span>
																</td>
																<td style="text-align:center; ">
																	<span style="font-family:Open Sans; ">
																		<xsl:text>Za plačnika:</xsl:text>
																	</span>
																</td>
															</tr>
															<tr>
																<td style="text-align:center; ">
																	<xsl:choose>
																		<xsl:when test="nboM:PotrdiloOZadrzanostiOdDela/Podatki/ZadnjiDanZadrzanosti/ZaDiagnozo=&apos;true&apos;">
																			<span style="font-family:Open Sans; font-weight:bold; ">
																				<xsl:text>DA</xsl:text>
																			</span>
																		</xsl:when>
																		<xsl:when test="nboM:PotrdiloOZadrzanostiOdDela/Podatki/ZadnjiDanZadrzanosti/ZaDiagnozo=&apos;false&apos;">
																			<span style="font-family:Open Sans; font-weight:bold; ">
																				<xsl:text>NE</xsl:text>
																			</span>
																		</xsl:when>
																	</xsl:choose>
																</td>
																<td style="text-align:center; ">
																	<xsl:choose>
																		<xsl:when test="nboM:PotrdiloOZadrzanostiOdDela/Podatki/ZadnjiDanZadrzanosti/ZaRazlog=&apos;true&apos;">
																			<span style="font-family:Open Sans; font-weight:bold; ">
																				<xsl:text>DA</xsl:text>
																			</span>
																		</xsl:when>
																		<xsl:when test="nboM:PotrdiloOZadrzanostiOdDela/Podatki/ZadnjiDanZadrzanosti/ZaRazlog=&apos;false&apos;">
																			<span style="font-family:Open Sans; font-weight:bold; ">
																				<xsl:text>NE</xsl:text>
																			</span>
																		</xsl:when>
																	</xsl:choose>
																</td>
																<td style="text-align:center; ">
																	<xsl:choose>
																		<xsl:when test="nboM:PotrdiloOZadrzanostiOdDela/Podatki/ZadnjiDanZadrzanosti/ZaPlacnika=&apos;true&apos;">
																			<span style="font-family:Open Sans; font-weight:bold; ">
																				<xsl:text>DA</xsl:text>
																			</span>
																		</xsl:when>
																		<xsl:when test="nboM:PotrdiloOZadrzanostiOdDela/Podatki/ZadnjiDanZadrzanosti/ZaPlacnika=&apos;false&apos;">
																			<span style="font-family:Open Sans; font-weight:bold; ">
																				<xsl:text>NE</xsl:text>
																			</span>
																		</xsl:when>
																	</xsl:choose>
																</td>
															</tr>
														</tbody>
													</table>
												</td>
												<td style="border-bottom-color:blue; border-bottom-style:none; border-left-color:blue; border-left-style:none; border-right-color:blue; border-right-style:none; border-top-color:blue; border-top-style:none; text-align:left; width:0.1in; "/>
												<td style="border-bottom-color:blue; border-bottom-style:solid; border-bottom-width:thin; border-left-color:blue; border-left-style:solid; border-left-width:thin; border-right-color:blue; border-right-style:solid; border-right-width:thin; border-top-color:blue; border-top-style:solid; border-top-width:thin; font-weight:normal; text-align:left; width:50%; " valign="top">
													<table style="border-collapse:collapse; font-family:Open Sans; font-size:10pt; " bgcolor="white" border="0">
														<xsl:variable name="altova:CurrContextGrid_18" select="."/>
														<tbody>
															<tr>
																<xsl:for-each select="nboM:PotrdiloOZadrzanostiOdDela">
																	<xsl:for-each select="Podatki">
																		<xsl:for-each select="PrviDanZadrzanosti">
																			<td style="text-align:left; ">
																				<span style="font-family:Open Sans; ">
																					<xsl:text>Prvi dan zadržanosti od: </xsl:text>
																				</span>
																				<xsl:for-each select="DatumPrvegaDneZadrzanosti">
																					<span style="font-family:Open Sans; font-weight:bold; ">
																						<xsl:variable name="altova:seqContentStrings_19">
																							<xsl:value-of select="format-number(number(substring(string(string(.)), 9, 2)), '00', 'format1')"/>
																							<xsl:text>.</xsl:text>
																							<xsl:value-of select="format-number(number(substring(string(string(.)), 6, 2)), '00', 'format1')"/>
																							<xsl:text>.</xsl:text>
																							<xsl:value-of select="format-number(number(substring(string(string(string(.))), 1, 4)), '0000', 'format1')"/>
																						</xsl:variable>
																						<xsl:variable name="altova:sContent_19" select="string($altova:seqContentStrings_19)"/>
																						<xsl:value-of select="$altova:sContent_19"/>
																					</span>
																				</xsl:for-each>
																			</td>
																		</xsl:for-each>
																	</xsl:for-each>
																</xsl:for-each>
															</tr>
															<tr>
																<xsl:for-each select="nboM:PotrdiloOZadrzanostiOdDela">
																	<xsl:for-each select="Podatki">
																		<xsl:for-each select="PrviDanZadrzanosti">
																			<td style="text-align:left; ">
																				<span style="font-family:Open Sans; ">
																					<xsl:text>Prejšnja zadržanost od dela-recidiv </xsl:text>
																				</span>
																				<br/>
																				<span style="font-family:Open Sans; ">
																					<xsl:text>od: </xsl:text>
																				</span>
																				<xsl:for-each select="PrejsnjaZadrzanostRecidiv">
																					<xsl:for-each select="DatumOd">
																						<span style="font-family:Open Sans; font-weight:bold; ">
																							<xsl:variable name="altova:seqContentStrings_20">
																								<xsl:value-of select="format-number(number(substring(string(string(.)), 9, 2)), '00', 'format1')"/>
																								<xsl:text>. </xsl:text>
																								<xsl:value-of select="format-number(number(substring(string(string(.)), 6, 2)), '00', 'format1')"/>
																								<xsl:text>. </xsl:text>
																								<xsl:value-of select="format-number(number(substring(string(string(string(.))), 1, 4)), '0000', 'format1')"/>
																							</xsl:variable>
																							<xsl:variable name="altova:sContent_20" select="string($altova:seqContentStrings_20)"/>
																							<xsl:value-of select="$altova:sContent_20"/>
																						</span>
																					</xsl:for-each>
																				</xsl:for-each>
																				<span>
																					<xsl:text> do: </xsl:text>
																				</span>
																				<xsl:for-each select="PrejsnjaZadrzanostRecidiv">
																					<xsl:for-each select="DatumDo">
																						<span style="font-family:Open Sans; font-weight:bold; ">
																							<xsl:variable name="altova:seqContentStrings_21">
																								<xsl:value-of select="format-number(number(substring(string(string(.)), 9, 2)), '00', 'format1')"/>
																								<xsl:text>. </xsl:text>
																								<xsl:value-of select="format-number(number(substring(string(string(.)), 6, 2)), '00', 'format1')"/>
																								<xsl:text>. </xsl:text>
																								<xsl:value-of select="format-number(number(substring(string(string(string(.))), 1, 4)), '0000', 'format1')"/>
																							</xsl:variable>
																							<xsl:variable name="altova:sContent_21" select="string($altova:seqContentStrings_21)"/>
																							<xsl:value-of select="$altova:sContent_21"/>
																						</span>
																					</xsl:for-each>
																				</xsl:for-each>
																			</td>
																		</xsl:for-each>
																	</xsl:for-each>
																</xsl:for-each>
															</tr>
														</tbody>
													</table>
												</td>
											</tr>
										</tbody>
									</table>
								</td>
							</tr>
						</tbody>
					</table>
					<xsl:if test="count(nboM:PotrdiloOZadrzanostiOdDela/Podatki/PovezanaOseba)">
						<table border="0" width="100%">
							<xsl:variable name="altova:CurrContextGrid_22" select="."/>
							<tbody>
								<tr>
									<td valign="middle">
										<table style="border-bottom-style:none; border-left-style:none; border-right-style:none; border-top-style:none; font-family:Open Sans; font-size:8pt; " border="1" width="100%">
											<xsl:variable name="altova:CurrContextGrid_23" select="."/>
											<tbody style="font-weight:normal; ">
												<tr>
													<td style="border-bottom-color:blue; border-bottom-style:none; border-left-color:blue; border-left-style:none; border-right-color:blue; border-right-style:none; border-top-color:blue; border-top-style:none; width:50%; " valign="middle">
														<div>
															<span style="color:gray; font-family:Open Sans; font-size:8pt; ">
																<xsl:text>&#160;</xsl:text>
															</span>
															<span style="color:#4472C4; font-family:Open Sans; font-size:8pt; ">
																<xsl:text>7 - POVEZANA OSEBA</xsl:text>
															</span>
														</div>
													</td>
													<td style="border-bottom-color:blue; border-bottom-style:none; border-left-color:blue; border-left-style:none; border-right-color:blue; border-right-style:none; border-top-color:blue; border-top-style:none; width:0.1in; "/>
													<td style="border-bottom-color:blue; border-bottom-style:none; border-left-color:blue; border-left-style:none; border-right-color:blue; border-right-style:none; border-top-color:blue; border-top-style:none; width:50%; "/>
												</tr>
												<tr>
													<td style="border-bottom-color:blue; border-bottom-style:solid; border-bottom-width:thin; border-left-color:blue; border-left-style:solid; border-left-width:thin; border-right-color:blue; border-right-style:solid; border-right-width:thin; border-top-color:blue; border-top-style:solid; border-top-width:thin; font-weight:normal; width:50%; " valign="top">
														<br/>
														<table style="font-family:Open Sans; font-size:10pt; " bgcolor="white" border="0">
															<xsl:variable name="altova:CurrContextGrid_24" select="."/>
															<tbody>
																<tr>
																	<xsl:for-each select="nboM:PotrdiloOZadrzanostiOdDela">
																		<xsl:for-each select="Podatki">
																			<xsl:for-each select="PovezanaOseba">
																				<td>
																					<span style="font-family:Open Sans; ">
																						<xsl:text>Vrsta povezane osebe: </xsl:text>
																					</span>
																					<xsl:for-each select="SifraVrstePovezaneOsebe">
																						<xsl:for-each select="@sifra">
																							<span style="font-family:Open Sans; font-weight:bold; ">
																								<xsl:value-of select="string(.)"/>
																							</span>
																						</xsl:for-each>
																					</xsl:for-each>
																					<xsl:choose>
																						<xsl:when test="/nboM:PotrdiloOZadrzanostiOdDela/Podatki/PovezanaOseba/SifraVrstePovezaneOsebe/@sifra=1">
																							<span>
																								<xsl:text>&#160;</xsl:text>
																							</span>
																							<span style="font-weight:bold; ">
																								<xsl:text>-</xsl:text>
																							</span>
																							<span style="font-family:Open Sans; font-weight:bold; ">
																								<xsl:text> PARTNER</xsl:text>
																							</span>
																						</xsl:when>
																						<xsl:when test="/nboM:PotrdiloOZadrzanostiOdDela/Podatki/PovezanaOseba/SifraVrstePovezaneOsebe/@sifra=2">
																							<span>
																								<xsl:text>&#160;</xsl:text>
																							</span>
																							<span style="font-weight:bold; ">
																								<xsl:text>-</xsl:text>
																							</span>
																							<span style="font-family:Open Sans; font-weight:bold; ">
																								<xsl:text> OTROK</xsl:text>
																							</span>
																						</xsl:when>
																						<xsl:when test="/nboM:PotrdiloOZadrzanostiOdDela/Podatki/PovezanaOseba/SifraVrstePovezaneOsebe/@sifra=3">
																							<span style="font-family:Open Sans; font-weight:bold; ">
																								<xsl:text> - DRUGO</xsl:text>
																							</span>
																						</xsl:when>
																					</xsl:choose>
																				</td>
																			</xsl:for-each>
																		</xsl:for-each>
																	</xsl:for-each>
																</tr>
																<tr>
																	<xsl:for-each select="nboM:PotrdiloOZadrzanostiOdDela">
																		<xsl:for-each select="Podatki">
																			<xsl:for-each select="PovezanaOseba">
																				<td>
																					<span style="font-family:Open Sans; ">
																						<xsl:text>Datum rojstva: </xsl:text>
																					</span>
																					<xsl:for-each select="DatumRojstva">
																						<span style="font-family:Open Sans; font-weight:bold; ">
																							<xsl:variable name="altova:seqContentStrings_25">
																								<xsl:value-of select="format-number(number(substring(string(string(.)), 9, 2)), '00', 'format1')"/>
																								<xsl:text>.</xsl:text>
																								<xsl:value-of select="format-number(number(substring(string(string(.)), 6, 2)), '00', 'format1')"/>
																								<xsl:text>.</xsl:text>
																								<xsl:value-of select="format-number(number(substring(string(string(string(.))), 1, 4)), '0000', 'format1')"/>
																							</xsl:variable>
																							<xsl:variable name="altova:sContent_25" select="string($altova:seqContentStrings_25)"/>
																							<xsl:value-of select="$altova:sContent_25"/>
																						</span>
																					</xsl:for-each>
																				</td>
																			</xsl:for-each>
																		</xsl:for-each>
																	</xsl:for-each>
																</tr>
																<tr>
																	<xsl:for-each select="nboM:PotrdiloOZadrzanostiOdDela">
																		<xsl:for-each select="Podatki">
																			<xsl:for-each select="PovezanaOseba">
																				<td>
																					<span style="font-family:Open Sans; ">
																						<xsl:text>Priimek in ime:</xsl:text>
																					</span>
																					<span>
																						<xsl:text>&#160;</xsl:text>
																					</span>
																					<xsl:for-each select="ImeOsebe">
																						<xsl:for-each select="Priimek1">
																							<span style="font-family:Open Sans; font-weight:bold; ">
																								<xsl:apply-templates/>
																							</span>
																						</xsl:for-each>
																					</xsl:for-each>
																					<xsl:if test="not(ImeOsebe/PriimekVezaj)">
																						<span>
																							<xsl:text>&#160;</xsl:text>
																						</span>
																					</xsl:if>
																					<xsl:for-each select="ImeOsebe">
																						<xsl:for-each select="PriimekVezaj">
																							<span style="font-family:Open Sans; font-weight:bold; ">
																								<xsl:apply-templates/>
																							</span>
																						</xsl:for-each>
																					</xsl:for-each>
																					<xsl:for-each select="ImeOsebe">
																						<xsl:for-each select="Priimek2">
																							<span style="font-family:Open Sans; font-weight:bold; ">
																								<xsl:apply-templates/>
																							</span>
																						</xsl:for-each>
																					</xsl:for-each>
																					<xsl:choose>
																						<xsl:when test="not(ImeOsebe/Priimek2)"/>
																						<xsl:when test="(ImeOsebe/Priimek2)">
																							<span>
																								<xsl:text>&#160;</xsl:text>
																							</span>
																						</xsl:when>
																					</xsl:choose>
																					<xsl:for-each select="ImeOsebe">
																						<xsl:for-each select="Ime1">
																							<span style="font-family:Open Sans; font-weight:bold; ">
																								<xsl:apply-templates/>
																							</span>
																						</xsl:for-each>
																					</xsl:for-each>
																					<xsl:choose>
																						<xsl:when test="not(ImeOsebe/ImeVezaj)">
																							<span>
																								<xsl:text>&#160;</xsl:text>
																							</span>
																						</xsl:when>
																						<xsl:when test="ImeOsebe/ImeVezaj"/>
																					</xsl:choose>
																					<xsl:for-each select="ImeOsebe">
																						<xsl:for-each select="ImeVezaj">
																							<span style="font-family:Open Sans; font-weight:bold; ">
																								<xsl:apply-templates/>
																							</span>
																						</xsl:for-each>
																					</xsl:for-each>
																					<xsl:for-each select="ImeOsebe">
																						<xsl:for-each select="Ime2">
																							<span style="font-family:Open Sans; font-weight:bold; ">
																								<xsl:apply-templates/>
																							</span>
																						</xsl:for-each>
																					</xsl:for-each>
																				</td>
																			</xsl:for-each>
																		</xsl:for-each>
																	</xsl:for-each>
																</tr>
															</tbody>
														</table>
													</td>
													<td style="border-bottom-color:blue; border-bottom-style:none; border-left-color:blue; border-left-style:none; border-right-color:blue; border-right-style:none; border-top-color:blue; border-top-style:none; width:0.1in; "/>
													<td style="border-bottom-color:blue; border-bottom-style:none; border-bottom-width:thin; border-left-color:blue; border-left-style:none; border-left-width:thin; border-right-color:blue; border-right-style:none; border-right-width:thin; border-top-color:blue; border-top-style:none; border-top-width:thin; font-weight:normal; width:50%; "/>
												</tr>
											</tbody>
										</table>
									</td>
								</tr>
							</tbody>
						</table>
					</xsl:if>
					<br/>
					<table border="0" width="100%">
						<xsl:variable name="altova:CurrContextGrid_26" select="."/>
						<tbody>
							<tr>
								<td>
									<table style="border-bottom-style:none; border-left-style:none; border-right-style:none; border-top-style:none; font-family:Open Sans; font-size:10pt; " border="1" width="100%">
										<xsl:variable name="altova:CurrContextGrid_27" select="."/>
										<tbody style="font-weight:normal; ">
											<tr>
												<td style="border-bottom-color:blue; border-bottom-style:none; border-left-color:blue; border-left-style:none; border-right-color:blue; border-right-style:none; border-top-color:blue; border-top-style:none; width:50%; " valign="top">
													<br/>
													<span style="font-family:Open Sans; ">
														<xsl:text>Dne:</xsl:text>
													</span>
													<span>
														<xsl:text>&#160;</xsl:text>
													</span>
													<xsl:for-each select="nboM:PotrdiloOZadrzanostiOdDela">
														<xsl:for-each select="Podatki">
															<xsl:for-each select="DatumIzdajePotrdila">
																<span style="font-family:Open Sans; font-weight:bold; ">
																	<xsl:variable name="altova:seqContentStrings_28">
																		<xsl:value-of select="format-number(number(substring(string(string(.)), 9, 2)), '00', 'format1')"/>
																		<xsl:text>. </xsl:text>
																		<xsl:value-of select="format-number(number(substring(string(string(.)), 6, 2)), '00', 'format1')"/>
																		<xsl:text>. </xsl:text>
																		<xsl:value-of select="format-number(number(substring(string(string(string(.))), 1, 4)), '0000', 'format1')"/>
																	</xsl:variable>
																	<xsl:variable name="altova:sContent_28" select="string($altova:seqContentStrings_28)"/>
																	<xsl:value-of select="$altova:sContent_28"/>
																</span>
															</xsl:for-each>
														</xsl:for-each>
													</xsl:for-each>
													<br/>
													<span style="font-family:Open Sans; ">
														<xsl:text>Kraj: </xsl:text>
													</span>
													<xsl:for-each select="nboM:PotrdiloOZadrzanostiOdDela">
														<xsl:for-each select="Podatki">
															<xsl:for-each select="KrajIzdajePotrdila">
																<span style="font-family:Open Sans; font-weight:bold; ">
																	<xsl:apply-templates/>
																</span>
															</xsl:for-each>
														</xsl:for-each>
													</xsl:for-each>
													<br/>
													<br/>
													<xsl:if test="count(nboM:PotrdiloOZadrzanostiOdDela/Podatki/Storno/@sifra)">
														<span style="color:red; font-family:Open Sans; font-size:12pt; font-weight:bold; ">
															<xsl:text>PREKLICAN</xsl:text>
														</span>
													</xsl:if>
													<br/>
												</td>
												<td style="border-bottom-color:blue; border-bottom-style:none; border-left-color:blue; border-left-style:none; border-right-color:blue; border-right-style:none; border-top-color:blue; border-top-style:none; width:0.1in; "/>
												<td style="border-bottom-color:blue; border-bottom-style:none; border-left-color:blue; border-left-style:none; border-right-color:blue; border-right-style:none; border-top-color:blue; border-top-style:none; width:50%; " valign="top">
													<br/>
													<span>
														<xsl:text>Podpisnik: </xsl:text>
													</span>
													<xsl:for-each select="nboM:PotrdiloOZadrzanostiOdDela">
														<xsl:for-each select="Podatki">
															<xsl:for-each select="Podpisnik">
																<span style="font-weight:bold; ">
																	<xsl:apply-templates/>
																</span>
															</xsl:for-each>
														</xsl:for-each>
													</xsl:for-each>
													<br/>
													<span style="font-family:Open Sans; ">
														<xsl:text>Čas e-podpisa:</xsl:text>
													</span>
													<span>
														<xsl:text>&#160;</xsl:text>
													</span>
													<xsl:if test="nboM:PotrdiloOZadrzanostiOdDela/ds:Signature">
														<span style="font-family:Open Sans; font-weight:bold; ">
															<xsl:variable name="altova:seqContentStrings_29">
																<xsl:value-of select="format-number(number(substring(string(substring-before( substring-after(string(normalize-space(nboM:PotrdiloOZadrzanostiOdDela/ds:Signature/ds:Object)), &apos;&apos;), &apos;Z&apos;)), 9, 2)), '00', 'format1')"/>
																<xsl:text>. </xsl:text>
																<xsl:value-of select="format-number(number(substring(string(substring-before( substring-after(string(normalize-space(nboM:PotrdiloOZadrzanostiOdDela/ds:Signature/ds:Object)), &apos;&apos;), &apos;Z&apos;)), 6, 2)), '00', 'format1')"/>
																<xsl:text>. </xsl:text>
																<xsl:value-of select="format-number(number(substring(string(string(substring-before( substring-after(string(normalize-space(nboM:PotrdiloOZadrzanostiOdDela/ds:Signature/ds:Object)), &apos;&apos;), &apos;Z&apos;))), 1, 4)), '0000', 'format1')"/>
																<xsl:text> </xsl:text>
																<xsl:value-of select="format-number(number(substring(string(substring-before( substring-after(string(normalize-space(nboM:PotrdiloOZadrzanostiOdDela/ds:Signature/ds:Object)), &apos;&apos;), &apos;Z&apos;)), 12, 2)), '00', 'format1')"/>
																<xsl:text>:</xsl:text>
																<xsl:value-of select="format-number(number(substring(string(substring-before( substring-after(string(normalize-space(nboM:PotrdiloOZadrzanostiOdDela/ds:Signature/ds:Object)), &apos;&apos;), &apos;Z&apos;)), 15, 2)), '00', 'format1')"/>
																<xsl:text>:</xsl:text>
																<xsl:choose>
																	<xsl:when test="contains(string(substring-before( substring-after(string(normalize-space(nboM:PotrdiloOZadrzanostiOdDela/ds:Signature/ds:Object)), &apos;&apos;), &apos;Z&apos;)), 'Z')">
																		<xsl:value-of select="format-number(number(substring-after(substring-after(substring-before(string(substring-before( substring-after(string(normalize-space(nboM:PotrdiloOZadrzanostiOdDela/ds:Signature/ds:Object)), &apos;&apos;), &apos;Z&apos;)), 'Z'), ':'), ':')), '00', 'format1')"/>
																	</xsl:when>
																	<xsl:when test="contains(string(substring-before( substring-after(string(normalize-space(nboM:PotrdiloOZadrzanostiOdDela/ds:Signature/ds:Object)), &apos;&apos;), &apos;Z&apos;)), '+')">
																		<xsl:value-of select="format-number(number(substring-after(substring-after(substring-before(string(substring-before( substring-after(string(normalize-space(nboM:PotrdiloOZadrzanostiOdDela/ds:Signature/ds:Object)), &apos;&apos;), &apos;Z&apos;)), '+'), ':'), ':')), '00', 'format1')"/>
																	</xsl:when>
																	<xsl:when test="contains(substring(string(substring-before( substring-after(string(normalize-space(nboM:PotrdiloOZadrzanostiOdDela/ds:Signature/ds:Object)), &apos;&apos;), &apos;Z&apos;)), 18), '-')">
																		<xsl:value-of select="format-number(number(substring-before(substring(string(substring-before( substring-after(string(normalize-space(nboM:PotrdiloOZadrzanostiOdDela/ds:Signature/ds:Object)), &apos;&apos;), &apos;Z&apos;)), 18), '-')), '00', 'format1')"/>
																	</xsl:when>
																	<xsl:otherwise>
																		<xsl:value-of select="format-number(number(substring(string(substring-before( substring-after(string(normalize-space(nboM:PotrdiloOZadrzanostiOdDela/ds:Signature/ds:Object)), &apos;&apos;), &apos;Z&apos;)), 18)), '00', 'format1')"/>
																	</xsl:otherwise>
																</xsl:choose>
															</xsl:variable>
															<xsl:variable name="altova:sContent_29" select="string($altova:seqContentStrings_29)"/>
															<xsl:value-of select="$altova:sContent_29"/>
														</span>
													</xsl:if>
													<br/>
												</td>
											</tr>
										</tbody>
									</table>
								</td>
							</tr>
						</tbody>
					</table>
				</xsl:for-each>
			</body>
		</html>
	</xsl:template>
</xsl:stylesheet>
